// Autogenerated from KST: please remove this line if doing any edits by hand!

package io.kaitai.struct.spec

import io.kaitai.struct.typing.*
import io.kaitai.struct.testformats.IndexSizes
import kotlin.test.*
import okio.FileSystem
import okio.Path.Companion.toPath
import okio.SYSTEM

class TestIndexSizes {
    val SRC_DIR = FileSystem.SYSTEM.canonicalize("../../../src/".toPath(true))

    @Test
    fun testIndexSizes() {
        val path = SRC_DIR.resolve("index_sizes.bin").toString()
        val r: IndexSizes = IndexSizes.fromFile(path)

        assertEquals(actual = r.qty(), expected = 3)
        assertEquals(actual = r.sizes()[0], expected = 1)
        assertEquals(actual = r.sizes()[1], expected = 8)
        assertEquals(actual = r.sizes()[2], expected = 4)
        assertEquals(actual = r.bufs()[0], expected = "A")
        assertEquals(actual = r.bufs()[1], expected = "BBBBBBBB")
        assertEquals(actual = r.bufs()[2], expected = "CCCC")
    }
}
