// Autogenerated from KST: please remove this line if doing any edits by hand!

package io.kaitai.struct.spec

import io.kaitai.struct.typing.*
import io.kaitai.struct.testformats.SwitchIntegers2
import kotlin.test.*
import okio.FileSystem
import okio.Path.Companion.toPath
import okio.SYSTEM

class TestSwitchIntegers2 {
    val SRC_DIR = FileSystem.SYSTEM.canonicalize("../../../src/".toPath(true))

    @Test
    fun testSwitchIntegers2() {
        val path = SRC_DIR.resolve("switch_integers.bin").toString()
        val r: SwitchIntegers2 = SwitchIntegers2.fromFile(path)

        assertEquals(actual = r.code(), expected = 1)
        assertEquals(actual = r.len(), expected = 7)
        assertEquals(actual = r.ham(), expected = byteArrayOf(2, 64, 64, 4, 55, 19, 0))
        assertEquals(actual = r.padding(), expected = 0)
        assertEquals(actual = r.lenModStr(), expected = "13")
    }
}
