// Autogenerated from KST: please remove this line if doing any edits by hand!

package io.kaitai.struct.spec

import io.kaitai.struct.typing.*
import io.kaitai.struct.testformats.CombineBytes
import kotlin.test.*
import okio.FileSystem
import okio.Path.Companion.toPath
import okio.SYSTEM

class TestCombineBytes {
    val SRC_DIR = FileSystem.SYSTEM.canonicalize("../../../src/".toPath(true))

    @Test
    fun testCombineBytes() {
        val path = SRC_DIR.resolve("term_strz.bin").toString()
        val r: CombineBytes = CombineBytes.fromFile(path)

        assertEquals(actual = r.bytesTerm(), expected = byteArrayOf(102, 111, 111))
        assertEquals(actual = r.bytesLimit(), expected = byteArrayOf(98, 97, 114, 124))
        assertEquals(actual = r.bytesEos(), expected = byteArrayOf(98, 97, 122, 64))
        assertEquals(actual = r.bytesCalc(), expected = byteArrayOf(82, 110, 68))
        assertEquals(actual = r.termOrLimit(), expected = byteArrayOf(102, 111, 111))
        assertEquals(actual = r.termOrEos(), expected = byteArrayOf(98, 97, 122, 64))
        assertEquals(actual = r.termOrCalc(), expected = byteArrayOf(102, 111, 111))
        assertEquals(actual = r.limitOrEos(), expected = byteArrayOf(98, 97, 114, 124))
        assertEquals(actual = r.limitOrCalc(), expected = byteArrayOf(82, 110, 68))
        assertEquals(actual = r.eosOrCalc(), expected = byteArrayOf(98, 97, 122, 64))
    }
}
