// Autogenerated from KST: please remove this line if doing any edits by hand!

package io.kaitai.struct.spec

import io.kaitai.struct.typing.*
import io.kaitai.struct.testformats.EnumNegative
import kotlin.test.*
import okio.FileSystem
import okio.Path.Companion.toPath
import okio.SYSTEM

class TestEnumNegative {
    val SRC_DIR = FileSystem.SYSTEM.canonicalize("../../../src/".toPath(true))

    @Test
    fun testEnumNegative() {
        val path = SRC_DIR.resolve("enum_negative.bin").toString()
        val r: EnumNegative = EnumNegative.fromFile(path)

        assertEquals(actual = r.f1(), expected = EnumNegative.Constants.NEGATIVE_ONE)
        assertEquals(actual = r.f2(), expected = EnumNegative.Constants.POSITIVE_ONE)
    }
}
