// Autogenerated from KST: please remove this line if doing any edits by hand!

package io.kaitai.struct.spec

import io.kaitai.struct.typing.*
import io.kaitai.struct.testformats.IntegersMinMax
import kotlin.test.*
import okio.FileSystem
import okio.Path.Companion.toPath
import okio.SYSTEM

class TestIntegersMinMax {
    val SRC_DIR = FileSystem.SYSTEM.canonicalize("../../../src/".toPath(true))

    @Test
    fun testIntegersMinMax() {
        val path = SRC_DIR.resolve("integers_min_max.bin").toString()
        val r: IntegersMinMax = IntegersMinMax.fromFile(path)

        assertEquals(actual = r.unsignedMin().u1(), expected = 0)
        assertEquals(actual = r.unsignedMin().u2le(), expected = 0)
        assertEquals(actual = r.unsignedMin().u4le(), expected = 0)
        assertEquals(actual = r.unsignedMin().u8le(), expected = 0)
        assertEquals(actual = r.unsignedMin().u2be(), expected = 0)
        assertEquals(actual = r.unsignedMin().u4be(), expected = 0)
        assertEquals(actual = r.unsignedMin().u8be(), expected = 0)
        assertEquals(actual = r.unsignedMax().u1(), expected = 255)
        assertEquals(actual = r.unsignedMax().u2le(), expected = 65535)
        assertEquals(actual = r.unsignedMax().u4le(), expected = 4294967295)
        assertEquals(actual = r.unsignedMax().u8le(), expected = 18446744073709551615U.toLong())
        assertEquals(actual = r.unsignedMax().u2be(), expected = 65535)
        assertEquals(actual = r.unsignedMax().u4be(), expected = 4294967295)
        assertEquals(actual = r.unsignedMax().u8be(), expected = 18446744073709551615U.toLong())
        assertEquals(actual = r.signedMin().s1(), expected = -128)
        assertEquals(actual = r.signedMin().s2le(), expected = -32768)
        assertEquals(actual = r.signedMin().s4le(), expected = -2147483647 - 1)
        assertEquals(actual = r.signedMin().s8le(), expected = -9223372036854775807 - 1)
        assertEquals(actual = r.signedMin().s2be(), expected = -32768)
        assertEquals(actual = r.signedMin().s4be(), expected = -2147483647 - 1)
        assertEquals(actual = r.signedMin().s8be(), expected = -9223372036854775807 - 1)
        assertEquals(actual = r.signedMax().s1(), expected = 127)
        assertEquals(actual = r.signedMax().s2le(), expected = 32767)
        assertEquals(actual = r.signedMax().s4le(), expected = 2147483647)
        assertEquals(actual = r.signedMax().s8le(), expected = 9223372036854775807)
        assertEquals(actual = r.signedMax().s2be(), expected = 32767)
        assertEquals(actual = r.signedMax().s4be(), expected = 2147483647)
        assertEquals(actual = r.signedMax().s8be(), expected = 9223372036854775807)
    }
}
