// Autogenerated from KST: please remove this line if doing any edits by hand!

package io.kaitai.struct.spec

import io.kaitai.struct.typing.*
import io.kaitai.struct.testformats.ExprStrEncodings
import kotlin.test.*
import okio.FileSystem
import okio.Path.Companion.toPath
import okio.SYSTEM

class TestExprStrEncodings {
    val SRC_DIR = FileSystem.SYSTEM.canonicalize("../../../src/".toPath(true))

    @Test
    fun testExprStrEncodings() {
        val path = SRC_DIR.resolve("str_encodings.bin").toString()
        val r: ExprStrEncodings = ExprStrEncodings.fromFile(path)

        assertEquals(actual = r.str1Eq(), expected = true)
        assertEquals(actual = r.str2Eq(), expected = true)
        assertEquals(actual = r.str3Eq(), expected = true)
        assertEquals(actual = r.str3EqStr2(), expected = true)
        assertEquals(actual = r.str4Eq(), expected = true)
        assertEquals(actual = r.str4GtStrCalc(), expected = true)
        assertEquals(actual = r.str4GtStrFromBytes(), expected = true)
    }
}
