// Autogenerated from KST: please remove this line if doing any edits by hand!

package io.kaitai.struct.spec

import io.kaitai.struct.typing.*
import io.kaitai.struct.testformats.EnumOfValueInst
import kotlin.test.*
import okio.FileSystem
import okio.Path.Companion.toPath
import okio.SYSTEM

class TestEnumOfValueInst {
    val SRC_DIR = FileSystem.SYSTEM.canonicalize("../../../src/".toPath(true))

    @Test
    fun testEnumOfValueInst() {
        val path = SRC_DIR.resolve("enum_0.bin").toString()
        val r: EnumOfValueInst = EnumOfValueInst.fromFile(path)

        assertEquals(actual = r.pet1(), expected = EnumOfValueInst.Animal.CAT)
        assertEquals(actual = r.pet2(), expected = EnumOfValueInst.Animal.CHICKEN)
        assertEquals(actual = r.pet3(), expected = EnumOfValueInst.Animal.DOG)
        assertEquals(actual = r.pet4(), expected = EnumOfValueInst.Animal.DOG)
    }
}
