// Autogenerated from KST: please remove this line if doing any edits by hand!

package io.kaitai.struct.spec

import io.kaitai.struct.typing.*
import io.kaitai.struct.testformats.EnumLongRangeS
import kotlin.test.*
import okio.FileSystem
import okio.Path.Companion.toPath
import okio.SYSTEM

class TestEnumLongRangeS {
    val SRC_DIR = FileSystem.SYSTEM.canonicalize("../../../src/".toPath(true))

    @Test
    fun testEnumLongRangeS() {
        val path = SRC_DIR.resolve("enum_long_range_s.bin").toString()
        val r: EnumLongRangeS = EnumLongRangeS.fromFile(path)

        assertEquals(actual = r.f1(), expected = EnumLongRangeS.Constants.LONG_MIN)
        assertEquals(actual = r.f2(), expected = EnumLongRangeS.Constants.INT_BELOW_MIN)
        assertEquals(actual = r.f3(), expected = EnumLongRangeS.Constants.INT_MIN)
        assertEquals(actual = r.f4(), expected = EnumLongRangeS.Constants.ZERO)
        assertEquals(actual = r.f5(), expected = EnumLongRangeS.Constants.INT_MAX)
        assertEquals(actual = r.f6(), expected = EnumLongRangeS.Constants.INT_OVER_MAX)
        assertEquals(actual = r.f7(), expected = EnumLongRangeS.Constants.LONG_MAX)
    }
}
