// Autogenerated from KST: please remove this line if doing any edits by hand!

package io.kaitai.struct.spec

import io.kaitai.struct.typing.*
import io.kaitai.struct.testformats.ExprCalcArrayOps
import kotlin.test.*
import okio.FileSystem
import okio.Path.Companion.toPath
import okio.SYSTEM

class TestExprCalcArrayOps {
    val SRC_DIR = FileSystem.SYSTEM.canonicalize("../../../src/".toPath(true))

    @Test
    fun testExprCalcArrayOps() {
        val path = SRC_DIR.resolve("fixed_struct.bin").toString()
        val r: ExprCalcArrayOps = ExprCalcArrayOps.fromFile(path)

        assertEquals(actual = r.intArraySize(), expected = 7)
        assertEquals(actual = r.intArrayFirst(), expected = 10)
        assertEquals(actual = r.intArrayMid(), expected = 25)
        assertEquals(actual = r.intArrayLast(), expected = 1000)
        assertEquals(actual = r.intArrayMin(), expected = 10)
        assertEquals(actual = r.intArrayMax(), expected = 1000)
        assertEquals(actual = r.doubleArraySize(), expected = 5)
        assertEquals(r.doubleArrayFirst(), 10.0, 1e-6)
        assertEquals(r.doubleArrayMid(), 25.0, 1e-6)
        assertEquals(r.doubleArrayLast(), 3.14159, 1e-6)
        assertEquals(r.doubleArrayMin(), 3.14159, 1e-6)
        assertEquals(r.doubleArrayMax(), 100.0, 1e-6)
        assertEquals(actual = r.strArraySize(), expected = 4)
        assertEquals(actual = r.strArrayFirst(), expected = "un")
        assertEquals(actual = r.strArrayMid(), expected = "deux")
        assertEquals(actual = r.strArrayLast(), expected = "quatre")
        assertEquals(actual = r.strArrayMin(), expected = "deux")
        assertEquals(actual = r.strArrayMax(), expected = "un")
    }
}
