// Autogenerated from KST: please remove this line if doing any edits by hand!

package io.kaitai.struct.spec

import io.kaitai.struct.typing.*
import io.kaitai.struct.testformats.EnumToIClassBorder1
import kotlin.test.*
import okio.FileSystem
import okio.Path.Companion.toPath
import okio.SYSTEM

class TestEnumToIClassBorder1 {
    val SRC_DIR = FileSystem.SYSTEM.canonicalize("../../../src/".toPath(true))

    @Test
    fun testEnumToIClassBorder1() {
        val path = SRC_DIR.resolve("enum_0.bin").toString()
        val r: EnumToIClassBorder1 = EnumToIClassBorder1.fromFile(path)

        assertEquals(actual = r.pet1(), expected = EnumToIClassBorder1.Animal.CAT)
        assertEquals(actual = r.pet2(), expected = EnumToIClassBorder1.Animal.CHICKEN)
        assertEquals(actual = r.checker().isDog(), expected = true)
    }
}
