// Autogenerated from KST: please remove this line if doing any edits by hand!

package io.kaitai.struct.spec

import io.kaitai.struct.typing.*
import io.kaitai.struct.testformats.ParamsPassArrayUsertype
import kotlin.test.*
import okio.FileSystem
import okio.Path.Companion.toPath
import okio.SYSTEM

class TestParamsPassArrayUsertype {
    val SRC_DIR = FileSystem.SYSTEM.canonicalize("../../../src/".toPath(true))

    @Test
    fun testParamsPassArrayUsertype() {
        val path = SRC_DIR.resolve("position_to_end.bin").toString()
        val r: ParamsPassArrayUsertype = ParamsPassArrayUsertype.fromFile(path)

        assertEquals(actual = r.passBlocks().bar().size, expected = 2)
        assertEquals(actual = r.passBlocks().bar()[0].foo(), expected = 1)
        assertEquals(actual = r.passBlocks().bar()[1].foo(), expected = 2)
        assertEquals(actual = r.passBlocks().one(), expected = byteArrayOf(3))
        assertEquals(actual = r.passBlocks().two(), expected = byteArrayOf(4, 5))
    }
}
