// Autogenerated from KST: please remove this line if doing any edits by hand!

package io.kaitai.struct.spec

import io.kaitai.struct.typing.*
import io.kaitai.struct.testformats.ExprStrOps
import kotlin.test.*
import okio.FileSystem
import okio.Path.Companion.toPath
import okio.SYSTEM

class TestExprStrOps {
    val SRC_DIR = FileSystem.SYSTEM.canonicalize("../../../src/".toPath(true))

    @Test
    fun testExprStrOps() {
        val path = SRC_DIR.resolve("term_strz.bin").toString()
        val r: ExprStrOps = ExprStrOps.fromFile(path)

        assertEquals(actual = r.one(), expected = "foo|b")
        assertEquals(actual = r.oneLen(), expected = 5)
        assertEquals(actual = r.oneRev(), expected = "b|oof")
        assertEquals(actual = r.oneSubstr0To3(), expected = "foo")
        assertEquals(actual = r.oneSubstr2To5(), expected = "o|b")
        assertEquals(actual = r.oneSubstr3To3(), expected = "")
        assertEquals(actual = r.two(), expected = "0123456789")
        assertEquals(actual = r.twoLen(), expected = 10)
        assertEquals(actual = r.twoRev(), expected = "9876543210")
        assertEquals(actual = r.twoSubstr0To7(), expected = "0123456")
        assertEquals(actual = r.twoSubstr4To10(), expected = "456789")
        assertEquals(actual = r.twoSubstr0To10(), expected = "0123456789")
        assertEquals(actual = r.toIAttr(), expected = 9173)
        assertEquals(actual = r.toIR10(), expected = -72)
        assertEquals(actual = r.toIR2(), expected = 86)
        assertEquals(actual = r.toIR8(), expected = 465)
        assertEquals(actual = r.toIR16(), expected = 18383)
    }
}
