// Autogenerated from KST: please remove this line if doing any edits by hand!

package io.kaitai.struct.spec

import io.kaitai.struct.typing.*
import io.kaitai.struct.testformats.BitsByteAligned
import kotlin.test.*
import okio.FileSystem
import okio.Path.Companion.toPath
import okio.SYSTEM

class TestBitsByteAligned {
    val SRC_DIR = FileSystem.SYSTEM.canonicalize("../../../src/".toPath(true))

    @Test
    fun testBitsByteAligned() {
        val path = SRC_DIR.resolve("fixed_struct.bin").toString()
        val r: BitsByteAligned = BitsByteAligned.fromFile(path)

        assertEquals(actual = r.one(), expected = 20)
        assertEquals(actual = r.byte1(), expected = 65)
        assertEquals(actual = r.two(), expected = 2)
        assertEquals(actual = r.three(), expected = false)
        assertEquals(actual = r.byte2(), expected = 75)
        assertEquals(actual = r.four(), expected = 2892)
        assertEquals(actual = r.byte3(), expected = byteArrayOf(-1))
        assertEquals(actual = r.fullByte(), expected = 255)
        assertEquals(actual = r.byte4(), expected = 80)
    }
}
