// Autogenerated from KST: please remove this line if doing any edits by hand!

package io.kaitai.struct.spec

import io.kaitai.struct.typing.*
import io.kaitai.struct.testformats.DefaultEndianExprIsBe
import kotlin.test.*
import okio.FileSystem
import okio.Path.Companion.toPath
import okio.SYSTEM

class TestDefaultEndianExprIsBe {
    val SRC_DIR = FileSystem.SYSTEM.canonicalize("../../../src/".toPath(true))

    @Test
    fun testDefaultEndianExprIsBe() {
        val path = SRC_DIR.resolve("endian_expr.bin").toString()
        val r: DefaultEndianExprIsBe = DefaultEndianExprIsBe.fromFile(path)

        assertEquals(actual = r.docs()[0].indicator(), expected = byteArrayOf(73, 73))
        assertEquals(actual = r.docs()[0].main().someInt(), expected = 66)
        assertEquals(actual = r.docs()[0].main().someIntBe(), expected = 66)
        assertEquals(actual = r.docs()[0].main().someIntLe(), expected = 66)
        assertEquals(actual = r.docs()[0].main().instInt(), expected = 66)
        assertEquals(actual = r.docs()[0].main().instSub().foo(), expected = 66)
        assertEquals(actual = r.docs()[1].indicator(), expected = byteArrayOf(77, 77))
        assertEquals(actual = r.docs()[1].main().someInt(), expected = 66)
        assertEquals(actual = r.docs()[1].main().someIntBe(), expected = 66)
        assertEquals(actual = r.docs()[1].main().someIntLe(), expected = 66)
        assertEquals(actual = r.docs()[1].main().instInt(), expected = 1107296256)
        assertEquals(actual = r.docs()[1].main().instSub().foo(), expected = 1107296256)
        assertEquals(actual = r.docs()[2].indicator(), expected = byteArrayOf(88, 88))
        assertEquals(actual = r.docs()[2].main().someInt(), expected = 1107296256)
        assertEquals(actual = r.docs()[2].main().someIntBe(), expected = 66)
        assertEquals(actual = r.docs()[2].main().someIntLe(), expected = 66)
        assertEquals(actual = r.docs()[2].main().instInt(), expected = 66)
        assertEquals(actual = r.docs()[2].main().instSub().foo(), expected = 66)
    }
}
