// Autogenerated from KST: please remove this line if doing any edits by hand!

package io.kaitai.struct.spec

import io.kaitai.struct.typing.*
import io.kaitai.struct.testformats.PositionInSeq
import kotlin.test.*
import okio.FileSystem
import okio.Path.Companion.toPath
import okio.SYSTEM

class TestPositionInSeq {
    val SRC_DIR = FileSystem.SYSTEM.canonicalize("../../../src/".toPath(true))

    @Test
    fun testPositionInSeq() {
        val path = SRC_DIR.resolve("position_in_seq.bin").toString()
        val r: PositionInSeq = PositionInSeq.fromFile(path)

        assertContentEquals(actual = r.numbers(), expected = arrayListOf(0 + 1, 2, 3))
    }
}
