// Autogenerated from KST: please remove this line if doing any edits by hand!

package io.kaitai.struct.spec

import io.kaitai.struct.typing.*
import io.kaitai.struct.testformats.InstanceUserArray
import kotlin.test.*
import okio.FileSystem
import okio.Path.Companion.toPath
import okio.SYSTEM

class TestInstanceUserArray {
    val SRC_DIR = FileSystem.SYSTEM.canonicalize("../../../src/".toPath(true))

    @Test
    fun testInstanceUserArray() {
        val path = SRC_DIR.resolve("instance_std_array.bin").toString()
        val r: InstanceUserArray = InstanceUserArray.fromFile(path)

        assertEquals(actual = r.ofs(), expected = 16)
        assertEquals(actual = r.qtyEntries(), expected = 3)
        assertEquals(actual = r.entrySize(), expected = 4)
        assertEquals(actual = r.userEntries()?.size, expected = 3)
        assertEquals(actual = r.userEntries()?.get(0)?.word1(), expected = 4369)
        assertEquals(actual = r.userEntries()?.get(0)?.word2(), expected = 4369)
        assertEquals(actual = r.userEntries()?.get(1)?.word1(), expected = 8738)
        assertEquals(actual = r.userEntries()?.get(1)?.word2(), expected = 8738)
        assertEquals(actual = r.userEntries()?.get(2)?.word1(), expected = 13107)
        assertEquals(actual = r.userEntries()?.get(2)?.word2(), expected = 13107)
    }
}
