// Autogenerated from KST: please remove this line if doing any edits by hand!

package io.kaitai.struct.spec

import io.kaitai.struct.typing.*
import io.kaitai.struct.testformats.BitsUnalignedB64Be
import kotlin.test.*
import okio.FileSystem
import okio.Path.Companion.toPath
import okio.SYSTEM

class TestBitsUnalignedB64Be {
    val SRC_DIR = FileSystem.SYSTEM.canonicalize("../../../src/".toPath(true))

    @Test
    fun testBitsUnalignedB64Be() {
        val path = SRC_DIR.resolve("process_xor_4.bin").toString()
        val r: BitsUnalignedB64Be = BitsUnalignedB64Be.fromFile(path)

        assertEquals(actual = r.a(), expected = true)
        assertEquals(actual = r.b(), expected = 15670070570729969769U.toLong())
        assertEquals(actual = r.c(), expected = 14)
    }
}
