// Autogenerated from KST: please remove this line if doing any edits by hand!

package io.kaitai.struct.spec

import io.kaitai.struct.typing.*
import io.kaitai.struct.testformats.NestedTypeParam
import kotlin.test.*
import okio.FileSystem
import okio.Path.Companion.toPath
import okio.SYSTEM

class TestNestedTypeParam {
    val SRC_DIR = FileSystem.SYSTEM.canonicalize("../../../src/".toPath(true))

    @Test
    fun testNestedTypeParam() {
        val path = SRC_DIR.resolve("term_strz.bin").toString()
        val r: NestedTypeParam = NestedTypeParam.fromFile(path)

        assertEquals(actual = r.mainSeq().myLen(), expected = 5)
        assertEquals(actual = r.mainSeq().body(), expected = "foo|b")
    }
}
