// Autogenerated from KST: please remove this line if doing any edits by hand!

package io.kaitai.struct.spec

import io.kaitai.struct.typing.*
import io.kaitai.struct.testformats.ImportsParamsDefArrayUsertypeImported
import kotlin.test.*
import okio.FileSystem
import okio.Path.Companion.toPath
import okio.SYSTEM

class TestImportsParamsDefArrayUsertypeImported {
    val SRC_DIR = FileSystem.SYSTEM.canonicalize("../../../src/".toPath(true))

    @Test
    fun testImportsParamsDefArrayUsertypeImported() {
        val path = SRC_DIR.resolve("process_xor_4.bin").toString()
        val r: ImportsParamsDefArrayUsertypeImported = ImportsParamsDefArrayUsertypeImported.fromFile(path)

        assertEquals(actual = r.hws().size, expected = 2)
        assertEquals(actual = r.hws()[0].one(), expected = 236)
        assertEquals(actual = r.hws()[1].one(), expected = 187)
        assertEquals(actual = r.two().hw0One(), expected = 236)
        assertEquals(actual = r.two().hw1One(), expected = 187)
    }
}
