// Autogenerated from KST: please remove this line if doing any edits by hand!

package io.kaitai.struct.spec

import io.kaitai.struct.typing.*
import io.kaitai.struct.testformats.StrPadTermEmpty
import kotlin.test.*
import okio.FileSystem
import okio.Path.Companion.toPath
import okio.SYSTEM

class TestStrPadTermEmpty {
    val SRC_DIR = FileSystem.SYSTEM.canonicalize("../../../src/".toPath(true))

    @Test
    fun testStrPadTermEmpty() {
        val path = SRC_DIR.resolve("str_pad_term_empty.bin").toString()
        val r: StrPadTermEmpty = StrPadTermEmpty.fromFile(path)

        assertEquals(actual = r.strPad(), expected = "")
        assertEquals(actual = r.strTerm(), expected = "")
        assertEquals(actual = r.strTermAndPad(), expected = "")
        assertEquals(actual = r.strTermInclude(), expected = "@")
    }
}
