// Autogenerated from KST: please remove this line if doing any edits by hand!

package io.kaitai.struct.spec

import io.kaitai.struct.typing.*
import io.kaitai.struct.testformats.DefaultBigEndian
import kotlin.test.*
import okio.FileSystem
import okio.Path.Companion.toPath
import okio.SYSTEM

class TestDefaultBigEndian {
    val SRC_DIR = FileSystem.SYSTEM.canonicalize("../../../src/".toPath(true))

    @Test
    fun testDefaultBigEndian() {
        val path = SRC_DIR.resolve("enum_0.bin").toString()
        val r: DefaultBigEndian = DefaultBigEndian.fromFile(path)

        assertEquals(actual = r.one(), expected = 117440512)
    }
}
