// Autogenerated from KST: please remove this line if doing any edits by hand!

package io.kaitai.struct.spec

import io.kaitai.struct.typing.*
import io.kaitai.struct.testformats.ExprArray
import kotlin.test.*
import okio.FileSystem
import okio.Path.Companion.toPath
import okio.SYSTEM

class TestExprArray {
    val SRC_DIR = FileSystem.SYSTEM.canonicalize("../../../src/".toPath(true))

    @Test
    fun testExprArray() {
        val path = SRC_DIR.resolve("expr_array.bin").toString()
        val r: ExprArray = ExprArray.fromFile(path)

        assertEquals(actual = r.aintSize(), expected = 4)
        assertEquals(actual = r.aintFirst(), expected = 7657765)
        assertEquals(actual = r.aintLast(), expected = 16272640)
        assertEquals(actual = r.aintMin(), expected = 49185)
        assertEquals(actual = r.aintMax(), expected = 1123362332)
        assertEquals(actual = r.afloatSize(), expected = 3)
        assertEquals(r.afloatFirst(), -2.6839530254859364E-121, 1e-6)
        assertEquals(r.afloatLast(), -1.1103359815095273E-175, 1e-6)
        assertEquals(r.afloatMin(), -8.754689149998834E+288, 1e-6)
        assertEquals(r.afloatMax(), -1.1103359815095273E-175, 1e-6)
        assertEquals(actual = r.astrSize(), expected = 3)
        assertEquals(actual = r.astrFirst(), expected = "foo")
        assertEquals(actual = r.astrLast(), expected = "baz")
        assertEquals(actual = r.astrMin(), expected = "bar")
        assertEquals(actual = r.astrMax(), expected = "foo")
    }
}
