// Autogenerated from KST: please remove this line if doing any edits by hand!

package io.kaitai.struct.spec

import io.kaitai.struct.typing.*
import io.kaitai.struct.testformats.BitsUnalignedB32Le
import kotlin.test.*
import okio.FileSystem
import okio.Path.Companion.toPath
import okio.SYSTEM

class TestBitsUnalignedB32Le {
    val SRC_DIR = FileSystem.SYSTEM.canonicalize("../../../src/".toPath(true))

    @Test
    fun testBitsUnalignedB32Le() {
        val path = SRC_DIR.resolve("process_xor_4.bin").toString()
        val r: BitsUnalignedB32Le = BitsUnalignedB32Le.fromFile(path)

        assertEquals(actual = r.a(), expected = false)
        assertEquals(actual = r.b(), expected = 173137398)
        assertEquals(actual = r.c(), expected = 69)
    }
}
