// Autogenerated from KST: please remove this line if doing any edits by hand!

package io.kaitai.struct.spec

import io.kaitai.struct.typing.*
import io.kaitai.struct.testformats.NavParentVsValueInst
import kotlin.test.*
import okio.FileSystem
import okio.Path.Companion.toPath
import okio.SYSTEM

class TestNavParentVsValueInst {
    val SRC_DIR = FileSystem.SYSTEM.canonicalize("../../../src/".toPath(true))

    @Test
    fun testNavParentVsValueInst() {
        val path = SRC_DIR.resolve("term_strz.bin").toString()
        val r: NavParentVsValueInst = NavParentVsValueInst.fromFile(path)

        assertEquals(actual = r.s1(), expected = "foo")
    }
}
