// Autogenerated from KST: please remove this line if doing any edits by hand!

package io.kaitai.struct.spec

import io.kaitai.struct.typing.*
import io.kaitai.struct.testformats.EnumImportSeq
import io.kaitai.struct.testformats.Enum0
import io.kaitai.struct.testformats.EnumDeep
import kotlin.test.*
import okio.FileSystem
import okio.Path.Companion.toPath
import okio.SYSTEM

class TestEnumImportSeq {
    val SRC_DIR = FileSystem.SYSTEM.canonicalize("../../../src/".toPath(true))

    @Test
    fun testEnumImportSeq() {
        val path = SRC_DIR.resolve("enum_0.bin").toString()
        val r: EnumImportSeq = EnumImportSeq.fromFile(path)

        assertEquals(actual = r.pet1(), expected = Enum0.Animal.CAT)
        assertEquals(actual = r.pet2(), expected = EnumDeep.Container1.Container2.Animal.HARE)
    }
}
