// Autogenerated from KST: please remove this line if doing any edits by hand!

package io.kaitai.struct.spec

import io.kaitai.struct.typing.*
import io.kaitai.struct.testformats.StrEncodings
import kotlin.test.*
import okio.FileSystem
import okio.Path.Companion.toPath
import okio.SYSTEM

class TestStrEncodings {
    val SRC_DIR = FileSystem.SYSTEM.canonicalize("../../../src/".toPath(true))

    @Test
    fun testStrEncodings() {
        val path = SRC_DIR.resolve("str_encodings.bin").toString()
        val r: StrEncodings = StrEncodings.fromFile(path)

        assertEquals(actual = r.str1(), expected = "Some ASCII")
        assertEquals(actual = r.str2(), expected = "\u3053\u3093\u306b\u3061\u306f")
        assertEquals(actual = r.str3(), expected = "\u3053\u3093\u306b\u3061\u306f")
        assertEquals(actual = r.str4(), expected = "\u2591\u2592\u2593")
    }
}
