// Autogenerated from KST: please remove this line if doing any edits by hand!

package io.kaitai.struct.spec

import io.kaitai.struct.typing.*
import io.kaitai.struct.testformats.IfValues
import kotlin.test.*
import okio.FileSystem
import okio.Path.Companion.toPath
import okio.SYSTEM

class TestIfValues {
    val SRC_DIR = FileSystem.SYSTEM.canonicalize("../../../src/".toPath(true))

    @Test
    fun testIfValues() {
        val path = SRC_DIR.resolve("fixed_struct.bin").toString()
        val r: IfValues = IfValues.fromFile(path)

        assertEquals(actual = r.codes()[0].opcode(), expected = 80)
        assertEquals(actual = r.codes()[0].halfOpcode(), expected = 40)
        assertEquals(actual = r.codes()[1].opcode(), expected = 65)
        assertNull(r.codes()[1].halfOpcode())
        assertEquals(actual = r.codes()[2].opcode(), expected = 67)
        assertNull(r.codes()[2].halfOpcode())
    }
}
