// Autogenerated from KST: please remove this line if doing any edits by hand!

package io.kaitai.struct.spec

import io.kaitai.struct.typing.*
import io.kaitai.struct.testformats.ProcessRepeatBytes
import kotlin.test.*
import okio.FileSystem
import okio.Path.Companion.toPath
import okio.SYSTEM

class TestProcessRepeatBytes {
    val SRC_DIR = FileSystem.SYSTEM.canonicalize("../../../src/".toPath(true))

    @Test
    fun testProcessRepeatBytes() {
        val path = SRC_DIR.resolve("process_xor_4.bin").toString()
        val r: ProcessRepeatBytes = ProcessRepeatBytes.fromFile(path)

        assertEquals(actual = r.bufs()[0], expected = byteArrayOf(114, 37, 61, -118, 20))
        assertEquals(actual = r.bufs()[1], expected = byteArrayOf(74, 82, -86, 16, 68))
    }
}
