// Autogenerated from KST: please remove this line if doing any edits by hand!

package io.kaitai.struct.spec

import io.kaitai.struct.typing.*
import io.kaitai.struct.testformats.EnumLongRangeU
import kotlin.test.*
import okio.FileSystem
import okio.Path.Companion.toPath
import okio.SYSTEM

class TestEnumLongRangeU {
    val SRC_DIR = FileSystem.SYSTEM.canonicalize("../../../src/".toPath(true))

    @Test
    fun testEnumLongRangeU() {
        val path = SRC_DIR.resolve("enum_long_range_u.bin").toString()
        val r: EnumLongRangeU = EnumLongRangeU.fromFile(path)

        assertEquals(actual = r.f1(), expected = EnumLongRangeU.Constants.ZERO)
        assertEquals(actual = r.f2(), expected = EnumLongRangeU.Constants.INT_MAX)
        assertEquals(actual = r.f3(), expected = EnumLongRangeU.Constants.INT_OVER_MAX)
        assertEquals(actual = r.f4(), expected = EnumLongRangeU.Constants.LONG_MAX)
    }
}
