// Autogenerated from KST: please remove this line if doing any edits by hand!

package io.kaitai.struct.spec

import io.kaitai.struct.typing.*
import io.kaitai.struct.testformats.YamlInts
import kotlin.test.*
import okio.FileSystem
import okio.Path.Companion.toPath
import okio.SYSTEM

class TestYamlInts {
    val SRC_DIR = FileSystem.SYSTEM.canonicalize("../../../src/".toPath(true))

    @Test
    fun testYamlInts() {
        val path = SRC_DIR.resolve("fixed_struct.bin").toString()
        val r: YamlInts = YamlInts.fromFile(path)

        assertEquals(actual = r.testU4Dec(), expected = 4294967295)
        assertEquals(actual = r.testU4Hex(), expected = 4294967295)
        assertEquals(actual = r.testU8Dec(), expected = 18446744073709551615U.toLong())
        assertEquals(actual = r.testU8Hex(), expected = 18446744073709551615U.toLong())
    }
}
