// Autogenerated from KST: please remove this line if doing any edits by hand!

package io.kaitai.struct.spec

import io.kaitai.struct.typing.*
import io.kaitai.struct.testformats.RepeatEosBit
import kotlin.test.*
import okio.FileSystem
import okio.Path.Companion.toPath
import okio.SYSTEM

class TestRepeatEosBit {
    val SRC_DIR = FileSystem.SYSTEM.canonicalize("../../../src/".toPath(true))

    @Test
    fun testRepeatEosBit() {
        val path = SRC_DIR.resolve("enum_0.bin").toString()
        val r: RepeatEosBit = RepeatEosBit.fromFile(path)

        assertEquals(actual = r.nibbles().size, expected = 16)
    }
}
