// Autogenerated from KST: please remove this line if doing any edits by hand!

package io.kaitai.struct.spec

import io.kaitai.struct.typing.*
import io.kaitai.struct.testformats.SwitchManualEnumInvalid
import kotlin.test.*
import okio.FileSystem
import okio.Path.Companion.toPath
import okio.SYSTEM

class TestSwitchManualEnumInvalid {
    val SRC_DIR = FileSystem.SYSTEM.canonicalize("../../../src/".toPath(true))

    @Test
    fun testSwitchManualEnumInvalid() {
        val path = SRC_DIR.resolve("enum_negative.bin").toString()
        val r: SwitchManualEnumInvalid = SwitchManualEnumInvalid.fromFile(path)

        assertEquals(actual = r.opcodes().size, expected = 2)
        assertEquals(actual = r.opcodes()[0].code(), expected = 255)
        assertNull(r.opcodes()[0].body())
        assertEquals(actual = r.opcodes()[1].code(), expected = 1)
        assertNull(r.opcodes()[1].body())
    }
}
