// Autogenerated from KST: please remove this line if doing any edits by hand!

package io.kaitai.struct.spec

import io.kaitai.struct.typing.*
import io.kaitai.struct.testformats.EofExceptionBytes
import kotlin.test.*
import io.kaitai.struct.KaitaiStream
import okio.FileSystem
import okio.Path.Companion.toPath
import okio.SYSTEM

class TestEofExceptionBytes {
    val SRC_DIR = FileSystem.SYSTEM.canonicalize("../../../src/".toPath(true))

    @Test
    fun testEofExceptionBytes() {
        assertFailsWith(okio.EOFException::class) {
            val path = SRC_DIR.resolve("term_strz.bin").toString()
            EofExceptionBytes.fromFile(path)
        }
    }
}
