// Autogenerated from KST: please remove this line if doing any edits by hand!

package io.kaitai.struct.spec

import io.kaitai.struct.typing.*
import io.kaitai.struct.testformats.ProcessToUser
import kotlin.test.*
import okio.FileSystem
import okio.Path.Companion.toPath
import okio.SYSTEM

class TestProcessToUser {
    val SRC_DIR = FileSystem.SYSTEM.canonicalize("../../../src/".toPath(true))

    @Test
    fun testProcessToUser() {
        val path = SRC_DIR.resolve("process_rotate.bin").toString()
        val r: ProcessToUser = ProcessToUser.fromFile(path)

        assertEquals(actual = r.buf1().str(), expected = "Hello")
    }
}
