// Autogenerated from KST: please remove this line if doing any edits by hand!

package io.kaitai.struct.spec

import io.kaitai.struct.typing.*
import io.kaitai.struct.testformats.ExprIoTernary
import kotlin.test.*
import okio.FileSystem
import okio.Path.Companion.toPath
import okio.SYSTEM

class TestExprIoTernary {
    val SRC_DIR = FileSystem.SYSTEM.canonicalize("../../../src/".toPath(true))

    @Test
    fun testExprIoTernary() {
        val path = SRC_DIR.resolve("term_strz.bin").toString()
        val r: ExprIoTernary = ExprIoTernary.fromFile(path)

        assertEquals(actual = r.oneOrTwoIoSize1(), expected = 8)
        assertEquals(actual = r.oneOrTwoIoSize2(), expected = 8)
        assertEquals(actual = r.oneOrTwoIoSizeAdd3(), expected = 11)
    }
}
