// Autogenerated from KST: please remove this line if doing any edits by hand!

package io.kaitai.struct.spec

import io.kaitai.struct.typing.*
import io.kaitai.struct.testformats.SwitchElseOnly
import kotlin.test.*
import okio.FileSystem
import okio.Path.Companion.toPath
import okio.SYSTEM

class TestSwitchElseOnly {
    val SRC_DIR = FileSystem.SYSTEM.canonicalize("../../../src/".toPath(true))

    @Test
    fun testSwitchElseOnly() {
        val path = SRC_DIR.resolve("switch_opcodes.bin").toString()
        val r: SwitchElseOnly = SwitchElseOnly.fromFile(path)

        assertEquals(actual = r.opcode(), expected = 83)
        assertEquals(actual = r.primByte(), expected = 102)
        assertEquals(actual = r.ut().value(), expected = byteArrayOf(114, 0, 73, 66))
    }
}
