// Autogenerated from KST: please remove this line if doing any edits by hand!

package io.kaitai.struct.spec

import io.kaitai.struct.typing.*
import io.kaitai.struct.testformats.Enum1
import kotlin.test.*
import okio.FileSystem
import okio.Path.Companion.toPath
import okio.SYSTEM

class TestEnum1 {
    val SRC_DIR = FileSystem.SYSTEM.canonicalize("../../../src/".toPath(true))

    @Test
    fun testEnum1() {
        val path = SRC_DIR.resolve("enum_0.bin").toString()
        val r: Enum1 = Enum1.fromFile(path)

        assertEquals(actual = r.main().submain().pet1(), expected = Enum1.MainObj.Animal.CAT)
        assertEquals(actual = r.main().submain().pet2(), expected = Enum1.MainObj.Animal.CHICKEN)
    }
}
