// Autogenerated from KST: please remove this line if doing any edits by hand!

package io.kaitai.struct.spec

import io.kaitai.struct.typing.*
import io.kaitai.struct.testformats.RepeatUntilS4
import kotlin.test.*
import okio.FileSystem
import okio.Path.Companion.toPath
import okio.SYSTEM

class TestRepeatUntilS4 {
    val SRC_DIR = FileSystem.SYSTEM.canonicalize("../../../src/".toPath(true))

    @Test
    fun testRepeatUntilS4() {
        val path = SRC_DIR.resolve("repeat_until_s4.bin").toString()
        val r: RepeatUntilS4 = RepeatUntilS4.fromFile(path)

        assertContentEquals(actual = r.entries(), expected = arrayListOf(66, 4919, -251658241, -1))
        assertEquals(actual = r.afterall(), expected = "foobar")
    }
}
