// Autogenerated from KST: please remove this line if doing any edits by hand!

package io.kaitai.struct.spec

import io.kaitai.struct.typing.*
import io.kaitai.struct.testformats.BitsEnum
import kotlin.test.*
import okio.FileSystem
import okio.Path.Companion.toPath
import okio.SYSTEM

class TestBitsEnum {
    val SRC_DIR = FileSystem.SYSTEM.canonicalize("../../../src/".toPath(true))

    @Test
    fun testBitsEnum() {
        val path = SRC_DIR.resolve("fixed_struct.bin").toString()
        val r: BitsEnum = BitsEnum.fromFile(path)

        assertEquals(actual = r.one(), expected = BitsEnum.Animal.PLATYPUS)
        assertEquals(actual = r.two(), expected = BitsEnum.Animal.HORSE)
        assertEquals(actual = r.three(), expected = BitsEnum.Animal.CAT)
    }
}
