// Autogenerated from KST: please remove this line if doing any edits by hand!

package io.kaitai.struct.spec

import io.kaitai.struct.typing.*
import io.kaitai.struct.testformats.ValidFailRangeBytes
import kotlin.test.*
import io.kaitai.struct.KaitaiStream
import okio.FileSystem
import okio.Path.Companion.toPath
import okio.SYSTEM

class TestValidFailRangeBytes {
    val SRC_DIR = FileSystem.SYSTEM.canonicalize("../../../src/".toPath(true))

    @Test
    fun testValidFailRangeBytes() {
        assertFailsWith(KaitaiStream.ValidationGreaterThanError::class) {
            val path = SRC_DIR.resolve("fixed_struct.bin").toString()
            ValidFailRangeBytes.fromFile(path)
        }
    }
}
