// Autogenerated from KST: please remove this line if doing any edits by hand!

package io.kaitai.struct.spec

import io.kaitai.struct.typing.*
import io.kaitai.struct.testformats.NestedSameName2
import kotlin.test.*
import okio.FileSystem
import okio.Path.Companion.toPath
import okio.SYSTEM

class TestNestedSameName2 {
    val SRC_DIR = FileSystem.SYSTEM.canonicalize("../../../src/".toPath(true))

    @Test
    fun testNestedSameName2() {
        val path = SRC_DIR.resolve("nested_same_name2.bin").toString()
        val r: NestedSameName2 = NestedSameName2.fromFile(path)

        assertEquals(actual = r.version(), expected = 66)
        assertEquals(actual = r.mainData().mainSize(), expected = 2)
        assertEquals(actual = r.mainData().foo().data1(), expected = byteArrayOf(17, 17, 17, 17))
        assertEquals(actual = r.dummy().dummySize(), expected = 3)
        assertEquals(actual = r.dummy().foo().data2(), expected = byteArrayOf(34, 34, 34, 34, 34, 34))
    }
}
