// Autogenerated from KST: please remove this line if doing any edits by hand!

package io.kaitai.struct.spec

import io.kaitai.struct.typing.*
import io.kaitai.struct.testformats.ProcessRepeatUsertype
import kotlin.test.*
import okio.FileSystem
import okio.Path.Companion.toPath
import okio.SYSTEM

class TestProcessRepeatUsertype {
    val SRC_DIR = FileSystem.SYSTEM.canonicalize("../../../src/".toPath(true))

    @Test
    fun testProcessRepeatUsertype() {
        val path = SRC_DIR.resolve("process_xor_4.bin").toString()
        val r: ProcessRepeatUsertype = ProcessRepeatUsertype.fromFile(path)

        assertEquals(actual = r.blocks()[0].a(), expected = -1975704206)
        assertEquals(actual = r.blocks()[0].b(), expected = 20)
        assertEquals(actual = r.blocks()[1].a(), expected = 279597642)
        assertEquals(actual = r.blocks()[1].b(), expected = 68)
    }
}
