// Autogenerated from KST: please remove this line if doing any edits by hand!

package io.kaitai.struct.spec

import io.kaitai.struct.typing.*
import io.kaitai.struct.testformats.ExprIfIntOps
import kotlin.test.*
import okio.FileSystem
import okio.Path.Companion.toPath
import okio.SYSTEM

class TestExprIfIntOps {
    val SRC_DIR = FileSystem.SYSTEM.canonicalize("../../../src/".toPath(true))

    @Test
    fun testExprIfIntOps() {
        val path = SRC_DIR.resolve("process_coerce_switch.bin").toString()
        val r: ExprIfIntOps = ExprIfIntOps.fromFile(path)

        assertEquals(actual = r.isEqPrim(), expected = true)
        assertEquals(actual = r.isEqBoxed(), expected = true)
    }
}
