// Autogenerated from KST: please remove this line if doing any edits by hand!

package io.kaitai.struct.spec

import io.kaitai.struct.typing.*
import io.kaitai.struct.testformats.EnumFancy
import kotlin.test.*
import okio.FileSystem
import okio.Path.Companion.toPath
import okio.SYSTEM

class TestEnumFancy {
    val SRC_DIR = FileSystem.SYSTEM.canonicalize("../../../src/".toPath(true))

    @Test
    fun testEnumFancy() {
        val path = SRC_DIR.resolve("enum_0.bin").toString()
        val r: EnumFancy = EnumFancy.fromFile(path)

        assertEquals(actual = r.pet1(), expected = EnumFancy.Animal.CAT)
        assertEquals(actual = r.pet2(), expected = EnumFancy.Animal.CHICKEN)
    }
}
