// Autogenerated from KST: please remove this line if doing any edits by hand!

package io.kaitai.struct.spec

import io.kaitai.struct.typing.*
import io.kaitai.struct.testformats.EnumToIInvalid
import kotlin.test.*
import okio.FileSystem
import okio.Path.Companion.toPath
import okio.SYSTEM

class TestEnumToIInvalid {
    val SRC_DIR = FileSystem.SYSTEM.canonicalize("../../../src/".toPath(true))

    @Test
    fun testEnumToIInvalid() {
        val path = SRC_DIR.resolve("term_strz.bin").toString()
        val r: EnumToIInvalid = EnumToIInvalid.fromFile(path)

        assertEquals(actual = r.pet1(), expected = EnumToIInvalid.Animal.DOG)
        assertEquals(actual = r.pet2(), expected = 111)
        assertEquals(actual = r.pet2I(), expected = 111)
        assertEquals(actual = r.pet2IToS(), expected = "111")
        assertEquals(actual = r.pet2Mod(), expected = 32879)
        assertEquals(actual = r.oneLtTwo(), expected = true)
        assertEquals(actual = r.pet2EqIntT(), expected = true)
        assertEquals(actual = r.pet2EqIntF(), expected = false)
    }
}
