// Autogenerated from KST: please remove this line if doing any edits by hand!

package io.kaitai.struct.spec

import io.kaitai.struct.typing.*
import io.kaitai.struct.testformats.SwitchManualIntElse
import kotlin.test.*
import okio.FileSystem
import okio.Path.Companion.toPath
import okio.SYSTEM

class TestSwitchManualIntElse {
    val SRC_DIR = FileSystem.SYSTEM.canonicalize("../../../src/".toPath(true))

    @Test
    fun testSwitchManualIntElse() {
        val path = SRC_DIR.resolve("switch_opcodes2.bin").toString()
        val r: SwitchManualIntElse = SwitchManualIntElse.fromFile(path)

        assertEquals(actual = r.opcodes().size, expected = 4)
        assertEquals(actual = r.opcodes()[0].code(), expected = 83)
        assertEquals(actual = (r.opcodes()[0].body() as SwitchManualIntElse.Opcode.Strval) /* generic cast */.value(), expected = "foo")
        assertEquals(actual = r.opcodes()[1].code(), expected = 88)
        assertEquals(actual = (r.opcodes()[1].body() as SwitchManualIntElse.Opcode.Noneval) /* generic cast */.filler(), expected = 66)
        assertEquals(actual = r.opcodes()[2].code(), expected = 89)
        assertEquals(actual = (r.opcodes()[2].body() as SwitchManualIntElse.Opcode.Noneval) /* generic cast */.filler(), expected = 51966)
        assertEquals(actual = r.opcodes()[3].code(), expected = 73)
        assertEquals(actual = (r.opcodes()[3].body() as SwitchManualIntElse.Opcode.Intval) /* generic cast */.value(), expected = 7)
    }
}
