// Autogenerated from KST: please remove this line if doing any edits by hand!

package io.kaitai.struct.spec

import io.kaitai.struct.typing.*
import io.kaitai.struct.testformats.ExprMod
import kotlin.test.*
import okio.FileSystem
import okio.Path.Companion.toPath
import okio.SYSTEM

class TestExprMod {
    val SRC_DIR = FileSystem.SYSTEM.canonicalize("../../../src/".toPath(true))

    @Test
    fun testExprMod() {
        val path = SRC_DIR.resolve("fixed_struct.bin").toString()
        val r: ExprMod = ExprMod.fromFile(path)

        assertEquals(actual = r.intU(), expected = 1262698832)
        assertEquals(actual = r.intS(), expected = -52947)
        assertEquals(actual = r.modPosConst(), expected = 9)
        assertEquals(actual = r.modNegConst(), expected = 4)
        assertEquals(actual = r.modPosSeq(), expected = 5)
        assertEquals(actual = r.modNegSeq(), expected = 2)
    }
}
