// Autogenerated from KST: please remove this line if doing any edits by hand!

package io.kaitai.struct.spec

import io.kaitai.struct.typing.*
import io.kaitai.struct.testformats.TypeTernary
import kotlin.test.*
import okio.FileSystem
import okio.Path.Companion.toPath
import okio.SYSTEM

class TestTypeTernary {
    val SRC_DIR = FileSystem.SYSTEM.canonicalize("../../../src/".toPath(true))

    @Test
    fun testTypeTernary() {
        val path = SRC_DIR.resolve("term_strz.bin").toString()
        val r: TypeTernary = TypeTernary.fromFile(path)

        assertEquals(actual = r.dif().value(), expected = 101)
    }
}
