// Autogenerated from KST: please remove this line if doing any edits by hand!

package io.kaitai.struct.spec

import io.kaitai.struct.typing.*
import io.kaitai.struct.testformats.NestedTypes
import kotlin.test.*
import okio.FileSystem
import okio.Path.Companion.toPath
import okio.SYSTEM

class TestNestedTypes {
    val SRC_DIR = FileSystem.SYSTEM.canonicalize("../../../src/".toPath(true))

    @Test
    fun testNestedTypes() {
        val path = SRC_DIR.resolve("fixed_struct.bin").toString()
        val r: NestedTypes = NestedTypes.fromFile(path)

        assertEquals(actual = r.one().typedAtRoot().valueB(), expected = 80)
        assertEquals(actual = r.one().typedHere().valueC(), expected = 65)
        assertEquals(actual = r.two().valueB(), expected = 67)
    }
}
