// Autogenerated from KST: please remove this line if doing any edits by hand!

package io.kaitai.struct.spec

import io.kaitai.struct.typing.*
import io.kaitai.struct.testformats.JsSignedRightShift
import kotlin.test.*
import okio.FileSystem
import okio.Path.Companion.toPath
import okio.SYSTEM

class TestJsSignedRightShift {
    val SRC_DIR = FileSystem.SYSTEM.canonicalize("../../../src/".toPath(true))

    @Test
    fun testJsSignedRightShift() {
        val path = SRC_DIR.resolve("fixed_struct.bin").toString()
        val r: JsSignedRightShift = JsSignedRightShift.fromFile(path)

        assertEquals(actual = r.shouldBe40000000(), expected = 1073741824)
        assertEquals(actual = r.shouldBeA00000(), expected = 10485760)
    }
}
