// Autogenerated from KST: please remove this line if doing any edits by hand!

package io.kaitai.struct.spec

import io.kaitai.struct.typing.*
import io.kaitai.struct.testformats.ImportsCircularA
import kotlin.test.*
import okio.FileSystem
import okio.Path.Companion.toPath
import okio.SYSTEM

class TestImportsCircularA {
    val SRC_DIR = FileSystem.SYSTEM.canonicalize("../../../src/".toPath(true))

    @Test
    fun testImportsCircularA() {
        val path = SRC_DIR.resolve("fixed_struct.bin").toString()
        val r: ImportsCircularA = ImportsCircularA.fromFile(path)

        assertEquals(actual = r.code(), expected = 80)
        assertEquals(actual = r.two().initial(), expected = 65)
        assertEquals(actual = r.two().backRef().code(), expected = 67)
        assertEquals(actual = r.two().backRef().two().initial(), expected = 75)
        assertNull(r.two().backRef().two().backRef())
    }
}
