// Autogenerated from KST: please remove this line if doing any edits by hand!

package io.kaitai.struct.spec

import io.kaitai.struct.typing.*
import io.kaitai.struct.testformats.EnumIntRangeS
import kotlin.test.*
import okio.FileSystem
import okio.Path.Companion.toPath
import okio.SYSTEM

class TestEnumIntRangeS {
    val SRC_DIR = FileSystem.SYSTEM.canonicalize("../../../src/".toPath(true))

    @Test
    fun testEnumIntRangeS() {
        val path = SRC_DIR.resolve("enum_int_range_s.bin").toString()
        val r: EnumIntRangeS = EnumIntRangeS.fromFile(path)

        assertEquals(actual = r.f1(), expected = EnumIntRangeS.Constants.INT_MIN)
        assertEquals(actual = r.f2(), expected = EnumIntRangeS.Constants.ZERO)
        assertEquals(actual = r.f3(), expected = EnumIntRangeS.Constants.INT_MAX)
    }
}
