// Autogenerated from KST: please remove this line if doing any edits by hand!

package io.kaitai.struct.spec

import io.kaitai.struct.typing.*
import io.kaitai.struct.testformats.ProcessXor4Const
import kotlin.test.*
import okio.FileSystem
import okio.Path.Companion.toPath
import okio.SYSTEM

class TestProcessXor4Const {
    val SRC_DIR = FileSystem.SYSTEM.canonicalize("../../../src/".toPath(true))

    @Test
    fun testProcessXor4Const() {
        val path = SRC_DIR.resolve("process_xor_4.bin").toString()
        val r: ProcessXor4Const = ProcessXor4Const.fromFile(path)

        assertEquals(actual = r.key(), expected = byteArrayOf(-20, -69, -93, 20))
        assertEquals(actual = r.buf(), expected = byteArrayOf(102, 111, 111, 32, 98, 97, 114))
    }
}
