// Autogenerated from KST: please remove this line if doing any edits by hand!

package io.kaitai.struct.spec

import io.kaitai.struct.typing.*
import io.kaitai.struct.testformats.TermStrz
import kotlin.test.*
import okio.FileSystem
import okio.Path.Companion.toPath
import okio.SYSTEM

class TestTermStrz {
    val SRC_DIR = FileSystem.SYSTEM.canonicalize("../../../src/".toPath(true))

    @Test
    fun testTermStrz() {
        val path = SRC_DIR.resolve("term_strz.bin").toString()
        val r: TermStrz = TermStrz.fromFile(path)

        assertEquals(actual = r.s1(), expected = "foo")
        assertEquals(actual = r.s2(), expected = "bar")
        assertEquals(actual = r.s3(), expected = "|baz@")
    }
}
