// Autogenerated from KST: please remove this line if doing any edits by hand!

package io.kaitai.struct.spec

import io.kaitai.struct.typing.*
import io.kaitai.struct.testformats.NestedTypes3
import kotlin.test.*
import okio.FileSystem
import okio.Path.Companion.toPath
import okio.SYSTEM

class TestNestedTypes3 {
    val SRC_DIR = FileSystem.SYSTEM.canonicalize("../../../src/".toPath(true))

    @Test
    fun testNestedTypes3() {
        val path = SRC_DIR.resolve("fixed_struct.bin").toString()
        val r: NestedTypes3 = NestedTypes3.fromFile(path)

        assertEquals(actual = r.aCc().valueCc(), expected = 80)
        assertEquals(actual = r.aCD().valueD(), expected = 65)
        assertEquals(actual = r.b().valueB(), expected = 67)
        assertEquals(actual = r.b().aCc().valueCc(), expected = 75)
        assertEquals(actual = r.b().aCD().valueD(), expected = 45)
    }
}
