// Autogenerated from KST: please remove this line if doing any edits by hand!

package io.kaitai.struct.spec

import io.kaitai.struct.typing.*
import io.kaitai.struct.testformats.ExprIoEof
import kotlin.test.*
import okio.FileSystem
import okio.Path.Companion.toPath
import okio.SYSTEM

class TestExprIoEof {
    val SRC_DIR = FileSystem.SYSTEM.canonicalize("../../../src/".toPath(true))

    @Test
    fun testExprIoEof() {
        val path = SRC_DIR.resolve("fixed_struct.bin").toString()
        val r: ExprIoEof = ExprIoEof.fromFile(path)

        assertEquals(actual = r.substream1().one(), expected = 1262698832)
        assertNull(r.substream1().two())
        assertEquals(actual = r.substream2().one(), expected = 4294914349)
        assertEquals(actual = r.substream2().two(), expected = 1262698832)
    }
}
