// Autogenerated from KST: please remove this line if doing any edits by hand!

package io.kaitai.struct.spec

import io.kaitai.struct.typing.*
import io.kaitai.struct.testformats.SwitchRepeatExpr
import kotlin.test.*
import okio.FileSystem
import okio.Path.Companion.toPath
import okio.SYSTEM

class TestSwitchRepeatExpr {
    val SRC_DIR = FileSystem.SYSTEM.canonicalize("../../../src/".toPath(true))

    @Test
    fun testSwitchRepeatExpr() {
        val path = SRC_DIR.resolve("switch_tlv.bin").toString()
        val r: SwitchRepeatExpr = SwitchRepeatExpr.fromFile(path)

        assertEquals(actual = r.code(), expected = 17)
        assertEquals(actual = r.size(), expected = 9)
        assertEquals(actual = (r.body()[0] as SwitchRepeatExpr.One) /* generic cast */.first(), expected = byteArrayOf(83, 116, 117, 102, 102, 0, 77, 101, 0))
    }
}
