// Autogenerated from KST: please remove this line if doing any edits by hand!

package io.kaitai.struct.spec

import io.kaitai.struct.typing.*
import io.kaitai.struct.testformats.FixedStruct
import kotlin.test.*
import okio.FileSystem
import okio.Path.Companion.toPath
import okio.SYSTEM

class TestFixedStruct {
    val SRC_DIR = FileSystem.SYSTEM.canonicalize("../../../src/".toPath(true))

    @Test
    fun testFixedStruct() {
        val path = SRC_DIR.resolve("fixed_struct.bin").toString()
        val r: FixedStruct = FixedStruct.fromFile(path)

        assertEquals(actual = r.hdr().uint8(), expected = 255)
        assertEquals(actual = r.hdr().uint16(), expected = 65535)
        assertEquals(actual = r.hdr().uint32(), expected = 4294967295)
        assertEquals(actual = r.hdr().uint64(), expected = 18446744073709551615U.toLong())
        assertEquals(actual = r.hdr().sint8(), expected = -1)
        assertEquals(actual = r.hdr().sint16(), expected = -1)
        assertEquals(actual = r.hdr().sint32(), expected = -1)
        assertEquals(actual = r.hdr().sint64(), expected = -1)
        assertEquals(actual = r.hdr().uint16le(), expected = 66)
        assertEquals(actual = r.hdr().uint32le(), expected = 66)
        assertEquals(actual = r.hdr().uint64le(), expected = 66)
        assertEquals(actual = r.hdr().sint16le(), expected = -66)
        assertEquals(actual = r.hdr().sint32le(), expected = -66)
        assertEquals(actual = r.hdr().sint64le(), expected = -66)
        assertEquals(actual = r.hdr().uint16be(), expected = 66)
        assertEquals(actual = r.hdr().uint32be(), expected = 66)
        assertEquals(actual = r.hdr().uint64be(), expected = 66)
        assertEquals(actual = r.hdr().sint16be(), expected = -66)
        assertEquals(actual = r.hdr().sint32be(), expected = -66)
        assertEquals(actual = r.hdr().sint64be(), expected = -66)
    }
}
