// Autogenerated from KST: please remove this line if doing any edits by hand!

package io.kaitai.struct.spec

import io.kaitai.struct.typing.*
import io.kaitai.struct.testformats.ExprBytesOps
import kotlin.test.*
import okio.FileSystem
import okio.Path.Companion.toPath
import okio.SYSTEM

class TestExprBytesOps {
    val SRC_DIR = FileSystem.SYSTEM.canonicalize("../../../src/".toPath(true))

    @Test
    fun testExprBytesOps() {
        val path = SRC_DIR.resolve("nav_parent_switch.bin").toString()
        val r: ExprBytesOps = ExprBytesOps.fromFile(path)

        assertEquals(actual = r.oneSize(), expected = 3)
        assertEquals(actual = r.oneFirst(), expected = 1)
        assertEquals(actual = r.oneMid(), expected = 66)
        assertEquals(actual = r.oneLast(), expected = 255)
        assertEquals(actual = r.oneLast().toString(), expected = "255")
        assertEquals(actual = r.oneMin(), expected = 1)
        assertEquals(actual = r.oneMax(), expected = 255)
        assertEquals(actual = r.oneMax().toString(), expected = "255")
        assertEquals(actual = r.twoSize(), expected = 3)
        assertEquals(actual = r.twoFirst(), expected = 65)
        assertEquals(actual = r.twoMid(), expected = 255)
        assertEquals(actual = r.twoMid().toString(), expected = "255")
        assertEquals(actual = r.twoLast(), expected = 75)
        assertEquals(actual = r.twoMin(), expected = 65)
        assertEquals(actual = r.twoMax(), expected = 255)
        assertEquals(actual = r.twoMax().toString(), expected = "255")
    }
}
