// Autogenerated from KST: please remove this line if doing any edits by hand!

package io.kaitai.struct.spec

import io.kaitai.struct.typing.*
import io.kaitai.struct.testformats.ExprBytesCmp
import kotlin.test.*
import okio.FileSystem
import okio.Path.Companion.toPath
import okio.SYSTEM

class TestExprBytesCmp {
    val SRC_DIR = FileSystem.SYSTEM.canonicalize("../../../src/".toPath(true))

    @Test
    fun testExprBytesCmp() {
        val path = SRC_DIR.resolve("fixed_struct.bin").toString()
        val r: ExprBytesCmp = ExprBytesCmp.fromFile(path)

        assertEquals(actual = r.one(), expected = byteArrayOf(80))
        assertEquals(actual = r.two(), expected = byteArrayOf(65, 67, 75))
        assertEquals(actual = r.isEq(), expected = true)
        assertEquals(actual = r.isNe(), expected = false)
        assertEquals(actual = r.isLt(), expected = true)
        assertEquals(actual = r.isGt(), expected = false)
        assertEquals(actual = r.isLe(), expected = true)
        assertEquals(actual = r.isGe(), expected = false)
        assertEquals(actual = r.isLt2(), expected = false)
        assertEquals(actual = r.isGt2(), expected = true)
    }
}
