// Autogenerated from KST: please remove this line if doing any edits by hand!

package io.kaitai.struct.spec

import io.kaitai.struct.typing.*
import io.kaitai.struct.testformats.InstanceIoUser
import kotlin.test.*
import okio.FileSystem
import okio.Path.Companion.toPath
import okio.SYSTEM

class TestInstanceIoUser {
    val SRC_DIR = FileSystem.SYSTEM.canonicalize("../../../src/".toPath(true))

    @Test
    fun testInstanceIoUser() {
        val path = SRC_DIR.resolve("instance_io.bin").toString()
        val r: InstanceIoUser = InstanceIoUser.fromFile(path)

        assertEquals(actual = r.qtyEntries(), expected = 3)
        assertEquals(actual = r.entries()[0].name(), expected = "the")
        assertEquals(actual = r.entries()[1].name(), expected = "rainy")
        assertEquals(actual = r.entries()[2].name(), expected = "day it is")
    }
}
