// Autogenerated from KST: please remove this line if doing any edits by hand!

package io.kaitai.struct.spec

import io.kaitai.struct.testformats.NavParentRecursive
import io.kaitai.struct.typing.*
import okio.FileSystem
import okio.Path.Companion.toPath
import okio.SYSTEM
import kotlin.test.*

class TestNavParentRecursive {
    val SRC_DIR = FileSystem.SYSTEM.canonicalize("../../../src/".toPath(true))

    @Test
    fun testNavParentRecursive() {
        val path = SRC_DIR.resolve("enum_negative.bin").toString()
        val r: NavParentRecursive = NavParentRecursive.fromFile(path)

        assertEquals(actual = r.value(), expected = 255)
        assertEquals(actual = r.next().value(), expected = 1)
        assertEquals(actual = r.next().parentValue(), expected = 255)
        assertFails { r.next().next() }
    }
}
