// Autogenerated from KST: please remove this line if doing any edits by hand!

package io.kaitai.struct.spec

import io.kaitai.struct.typing.*
import io.kaitai.struct.testformats.ZlibWithHeader78
import kotlin.test.*
import okio.FileSystem
import okio.Path.Companion.toPath
import okio.SYSTEM

class TestZlibWithHeader78 {
    val SRC_DIR = FileSystem.SYSTEM.canonicalize("../../../src/".toPath(true))

    @Test
    fun testZlibWithHeader78() {
        val path = SRC_DIR.resolve("zlib_with_header_78.bin").toString()
        val r: ZlibWithHeader78 = ZlibWithHeader78.fromFile(path)

        assertEquals(actual = r.data(), expected = byteArrayOf(97, 32, 113, 117, 105, 99, 107, 32, 98, 114, 111, 119, 110, 32, 102, 111, 120, 32, 106, 117, 109, 112, 115, 32, 111, 118, 101, 114))
    }
}
