// Autogenerated from KST: please remove this line if doing any edits by hand!

package io.kaitai.struct.spec

import io.kaitai.struct.typing.*
import io.kaitai.struct.testformats.ZlibSurrounded
import kotlin.test.*
import okio.FileSystem
import okio.Path.Companion.toPath
import okio.SYSTEM

class TestZlibSurrounded {
    val SRC_DIR = FileSystem.SYSTEM.canonicalize("../../../src/".toPath(true))

    @Test
    fun testZlibSurrounded() {
        val path = SRC_DIR.resolve("zlib_surrounded.bin").toString()
        val r: ZlibSurrounded = ZlibSurrounded.fromFile(path)

        assertEquals(actual = r.zlib().num(), expected = -1)
    }
}
