// Autogenerated from KST: please remove this line if doing any edits by hand!

package io.kaitai.struct.spec

import io.kaitai.struct.typing.*
import io.kaitai.struct.testformats.ExprBytesNonLiteral
import kotlin.test.*
import okio.FileSystem
import okio.Path.Companion.toPath
import okio.SYSTEM

class TestExprBytesNonLiteral {
    val SRC_DIR = FileSystem.SYSTEM.canonicalize("../../../src/".toPath(true))

    @Test
    fun testExprBytesNonLiteral() {
        val path = SRC_DIR.resolve("enum_negative.bin").toString()
        val r: ExprBytesNonLiteral = ExprBytesNonLiteral.fromFile(path)

        assertEquals(actual = r.calcBytes().size, expected = 2)
        assertEquals(actual = r.calcBytes()[0], expected = 255)
        assertEquals(actual = r.calcBytes()[1], expected = 1)
    }
}
