// Autogenerated from KST: please remove this line if doing any edits by hand!

package io.kaitai.struct.spec

import io.kaitai.struct.typing.*
import io.kaitai.struct.testformats.EnumDeepLiterals
import kotlin.test.*
import okio.FileSystem
import okio.Path.Companion.toPath
import okio.SYSTEM

class TestEnumDeepLiterals {
    val SRC_DIR = FileSystem.SYSTEM.canonicalize("../../../src/".toPath(true))

    @Test
    fun testEnumDeepLiterals() {
        val path = SRC_DIR.resolve("enum_0.bin").toString()
        val r: EnumDeepLiterals = EnumDeepLiterals.fromFile(path)

        assertEquals(actual = r.isPet1Ok(), expected = true)
        assertEquals(actual = r.isPet2Ok(), expected = true)
    }
}
