// Autogenerated from KST: please remove this line if doing any edits by hand!

package io.kaitai.struct.spec

import io.kaitai.struct.typing.*
import io.kaitai.struct.testformats.CombineStr
import kotlin.test.*
import okio.FileSystem
import okio.Path.Companion.toPath
import okio.SYSTEM

class TestCombineStr {
    val SRC_DIR = FileSystem.SYSTEM.canonicalize("../../../src/".toPath(true))

    @Test
    fun testCombineStr() {
        val path = SRC_DIR.resolve("term_strz.bin").toString()
        val r: CombineStr = CombineStr.fromFile(path)

        assertEquals(actual = r.strTerm(), expected = "foo")
        assertEquals(actual = r.strLimit(), expected = "bar|")
        assertEquals(actual = r.strEos(), expected = "baz@")
        assertEquals(actual = r.strCalc(), expected = "bar")
        assertEquals(actual = r.strCalcBytes(), expected = "baz")
        assertEquals(actual = r.termOrLimit(), expected = "foo")
        assertEquals(actual = r.termOrEos(), expected = "baz@")
        assertEquals(actual = r.termOrCalc(), expected = "foo")
        assertEquals(actual = r.termOrCalcBytes(), expected = "baz")
        assertEquals(actual = r.limitOrEos(), expected = "bar|")
        assertEquals(actual = r.limitOrCalc(), expected = "bar")
        assertEquals(actual = r.limitOrCalcBytes(), expected = "bar|")
        assertEquals(actual = r.eosOrCalc(), expected = "bar")
        assertEquals(actual = r.eosOrCalcBytes(), expected = "baz@")
        assertEquals(actual = r.calcOrCalcBytes(), expected = "baz")
    }
}
