// Autogenerated from KST: please remove this line if doing any edits by hand!

package io.kaitai.struct.spec

import io.kaitai.struct.typing.*
import io.kaitai.struct.testformats.BytesPadTerm
import kotlin.test.*
import okio.FileSystem
import okio.Path.Companion.toPath
import okio.SYSTEM

class TestBytesPadTerm {
    val SRC_DIR = FileSystem.SYSTEM.canonicalize("../../../src/".toPath(true))

    @Test
    fun testBytesPadTerm() {
        val path = SRC_DIR.resolve("str_pad_term.bin").toString()
        val r: BytesPadTerm = BytesPadTerm.fromFile(path)

        assertEquals(actual = r.strPad(), expected = byteArrayOf(115, 116, 114, 49))
        assertEquals(actual = r.strTerm(), expected = byteArrayOf(115, 116, 114, 50, 102, 111, 111))
        assertEquals(actual = r.strTermAndPad(), expected = byteArrayOf(115, 116, 114, 43, 43, 43, 51, 98, 97, 114, 43, 43, 43))
        assertEquals(actual = r.strTermInclude(), expected = byteArrayOf(115, 116, 114, 52, 98, 97, 122, 64))
    }
}
