// Autogenerated from KST: please remove this line if doing any edits by hand!

package io.kaitai.struct.spec

import io.kaitai.struct.typing.*
import io.kaitai.struct.testformats.NestedTypes2
import kotlin.test.*
import okio.FileSystem
import okio.Path.Companion.toPath
import okio.SYSTEM

class TestNestedTypes2 {
    val SRC_DIR = FileSystem.SYSTEM.canonicalize("../../../src/".toPath(true))

    @Test
    fun testNestedTypes2() {
        val path = SRC_DIR.resolve("fixed_struct.bin").toString()
        val r: NestedTypes2 = NestedTypes2.fromFile(path)

        assertEquals(actual = r.one().typedAtRoot().valueB(), expected = 80)
        assertEquals(actual = r.one().typedHere1().valueC(), expected = 65)
        assertEquals(actual = r.one().typedHere1().typedHere().valueD(), expected = 67)
        assertEquals(actual = r.one().typedHere1().typedParent().valueCc(), expected = 75)
        assertEquals(actual = r.one().typedHere1().typedRoot().valueB(), expected = 45)
        assertEquals(actual = r.one().typedHere2().valueCc(), expected = 49)
        assertEquals(actual = r.two().valueB(), expected = -1)
    }
}
