// Autogenerated from KST: please remove this line if doing any edits by hand!

package io.kaitai.struct.spec

import io.kaitai.struct.typing.*
import io.kaitai.struct.testformats.ValidEqStrEncodings
import kotlin.test.*
import okio.FileSystem
import okio.Path.Companion.toPath
import okio.SYSTEM

class TestValidEqStrEncodings {
    val SRC_DIR = FileSystem.SYSTEM.canonicalize("../../../src/".toPath(true))

    @Test
    fun testValidEqStrEncodings() {
        val path = SRC_DIR.resolve("str_encodings.bin").toString()
        val r: ValidEqStrEncodings = ValidEqStrEncodings.fromFile(path)

    }
}
