// Autogenerated from KST: please remove this line if doing any edits by hand!

package io.kaitai.struct.spec

import io.kaitai.struct.typing.*
import io.kaitai.struct.testformats.CastToTop
import kotlin.test.*
import okio.FileSystem
import okio.Path.Companion.toPath
import okio.SYSTEM

class TestCastToTop {
    val SRC_DIR = FileSystem.SYSTEM.canonicalize("../../../src/".toPath(true))

    @Test
    fun testCastToTop() {
        val path = SRC_DIR.resolve("fixed_struct.bin").toString()
        val r: CastToTop = CastToTop.fromFile(path)

        assertEquals(actual = r.code(), expected = 80)
        assertEquals(actual = r.header().code(), expected = 65)
        assertEquals(actual = r.headerCasted().code(), expected = 65)
    }
}
