// Autogenerated from KST: please remove this line if doing any edits by hand!

package io.kaitai.struct.spec

import io.kaitai.struct.typing.*
import io.kaitai.struct.testformats.ProcessCustomNoArgs
import kotlin.test.*
import okio.FileSystem
import okio.Path.Companion.toPath
import okio.SYSTEM

class TestProcessCustomNoArgs {
    val SRC_DIR = FileSystem.SYSTEM.canonicalize("../../../src/".toPath(true))

    @Test
    fun testProcessCustomNoArgs() {
        val path = SRC_DIR.resolve("process_rotate.bin").toString()
        val r: ProcessCustomNoArgs = ProcessCustomNoArgs.fromFile(path)

        assertEquals(actual = r.buf(), expected = byteArrayOf(95, 9, -84, -115, -115, -19, 95))
    }
}
