// Autogenerated from KST: please remove this line if doing any edits by hand!

package io.kaitai.struct.spec

import io.kaitai.struct.typing.*
import io.kaitai.struct.testformats.NavParent3
import kotlin.test.*
import okio.FileSystem
import okio.Path.Companion.toPath
import okio.SYSTEM

class TestNavParent3 {
    val SRC_DIR = FileSystem.SYSTEM.canonicalize("../../../src/".toPath(true))

    @Test
    fun testNavParent3() {
        val path = SRC_DIR.resolve("nav_parent2.bin").toString()
        val r: NavParent3 = NavParent3.fromFile(path)

        assertEquals(actual = r.ofsTags(), expected = 8)
        assertEquals(actual = r.numTags(), expected = 2)
        assertEquals(actual = r.tags()[0].name(), expected = "RAHC")
        assertEquals(actual = r.tags()[0].ofs(), expected = 32)
        assertEquals(actual = r.tags()[0].numItems(), expected = 3)
        assertEquals(actual = r.tags()[0].tagContent()?.content(), expected = "foo")
        assertEquals(actual = r.tags()[1].name(), expected = "RAHC")
        assertEquals(actual = r.tags()[1].ofs(), expected = 35)
        assertEquals(actual = r.tags()[1].numItems(), expected = 6)
        assertEquals(actual = r.tags()[1].tagContent()?.content(), expected = "barbaz")
    }
}
