// Autogenerated from KST: please remove this line if doing any edits by hand!

package io.kaitai.struct.spec

import io.kaitai.struct.typing.*
import io.kaitai.struct.testformats.ExprFstring0
import kotlin.test.*
import okio.FileSystem
import okio.Path.Companion.toPath
import okio.SYSTEM

class TestExprFstring0 {
    val SRC_DIR = FileSystem.SYSTEM.canonicalize("../../../src/".toPath(true))

    @Test
    fun testExprFstring0() {
        val path = SRC_DIR.resolve("term_strz.bin").toString()
        val r: ExprFstring0 = ExprFstring0.fromFile(path)

        assertEquals(actual = r.seqStr(), expected = "foo|b")
        assertEquals(actual = r.seqInt(), expected = 97)
        assertEquals(actual = r.empty(), expected = "")
        assertEquals(actual = r.literal(), expected = "abc")
        assertEquals(actual = r.literalWithEscapes(), expected = "abc\n\tt")
        assertEquals(actual = r.headAndIntLiteral(), expected = "abc=123")
        assertEquals(actual = r.headAndStrLiteral(), expected = "abc=foo")
        assertEquals(actual = r.headAndInt(), expected = "abc=97")
        assertEquals(actual = r.headAndStr(), expected = "abc=foo|b")
    }
}
