// Autogenerated from KST: please remove this line if doing any edits by hand!

package io.kaitai.struct.spec

import io.kaitai.struct.typing.*
import io.kaitai.struct.testformats.ParamsPassUsertype
import kotlin.test.*
import okio.FileSystem
import okio.Path.Companion.toPath
import okio.SYSTEM

class TestParamsPassUsertype {
    val SRC_DIR = FileSystem.SYSTEM.canonicalize("../../../src/".toPath(true))

    @Test
    fun testParamsPassUsertype() {
        val path = SRC_DIR.resolve("position_in_seq.bin").toString()
        val r: ParamsPassUsertype = ParamsPassUsertype.fromFile(path)

        assertEquals(actual = r.first().foo(), expected = 1)
        assertEquals(actual = r.one().buf(), expected = byteArrayOf(2))
    }
}
