// Autogenerated from KST: please remove this line if doing any edits by hand!

package io.kaitai.struct.spec

import io.kaitai.struct.typing.*
import io.kaitai.struct.testformats.ProcessCoerceSwitch
import kotlin.test.*
import okio.FileSystem
import okio.Path.Companion.toPath
import okio.SYSTEM

class TestProcessCoerceSwitch {
    val SRC_DIR = FileSystem.SYSTEM.canonicalize("../../../src/".toPath(true))

    @Test
    fun testProcessCoerceSwitch() {
        val path = SRC_DIR.resolve("process_coerce_switch.bin").toString()
        val r: ProcessCoerceSwitch = ProcessCoerceSwitch.fromFile(path)

        assertEquals(actual = r.bufType(), expected = 0)
        assertEquals(actual = r.flag(), expected = 0)
        assertEquals(actual = (r.buf() as ProcessCoerceSwitch.Foo) /* generic cast */.bar(), expected = byteArrayOf(65, 65, 65, 65))
    }
}
