// Autogenerated from KST: please remove this line if doing any edits by hand!

package io.kaitai.struct.spec

import io.kaitai.struct.typing.*
import io.kaitai.struct.testformats.TypeIntUnaryOp
import kotlin.test.*
import okio.FileSystem
import okio.Path.Companion.toPath
import okio.SYSTEM

class TestTypeIntUnaryOp {
    val SRC_DIR = FileSystem.SYSTEM.canonicalize("../../../src/".toPath(true))

    @Test
    fun testTypeIntUnaryOp() {
        val path = SRC_DIR.resolve("fixed_struct.bin").toString()
        val r: TypeIntUnaryOp = TypeIntUnaryOp.fromFile(path)

        assertEquals(actual = r.valueS2(), expected = 16720)
        assertEquals(actual = r.valueS8(), expected = 4706543082108963651)
        assertEquals(actual = r.unaryS2(), expected = -16720)
        assertEquals(actual = r.unaryS8(), expected = -4706543082108963651)
    }
}
