// Autogenerated from KST: please remove this line if doing any edits by hand!

package io.kaitai.struct.spec

import io.kaitai.struct.typing.*
import io.kaitai.struct.testformats.Expr2
import kotlin.test.*
import okio.FileSystem
import okio.Path.Companion.toPath
import okio.SYSTEM

class TestExpr2 {
    val SRC_DIR = FileSystem.SYSTEM.canonicalize("../../../src/".toPath(true))

    @Test
    fun testExpr2() {
        val path = SRC_DIR.resolve("str_encodings.bin").toString()
        val r: Expr2 = Expr2.fromFile(path)

        assertEquals(actual = r.str1().lenOrig(), expected = 10)
        assertEquals(actual = r.str1().lenMod(), expected = 7)
        assertEquals(actual = r.str1().str(), expected = "Some AS")
        assertEquals(actual = r.str1Len(), expected = 7)
        assertEquals(actual = r.str1LenMod(), expected = 7)
        assertEquals(actual = r.str1Byte1(), expected = 73)
        assertEquals(actual = r.str1Avg(), expected = 73)
        assertEquals(actual = r.str1Char5(), expected = "e")
        assertEquals(actual = r.str1Tuple5().byte0(), expected = 101)
        assertEquals(actual = r.str1Tuple5().byte0(), expected = 101)
        assertEquals(actual = r.str1Tuple5().byte1(), expected = 32)
        assertEquals(actual = r.str1Tuple5().byte2(), expected = 65)
        assertEquals(actual = r.str1Tuple5().avg(), expected = 48)
        assertEquals(actual = r.str2Tuple5().byte0(), expected = 101)
        assertEquals(actual = r.str2Tuple5().byte1(), expected = 32)
        assertEquals(actual = r.str2Tuple5().byte2(), expected = 65)
        assertEquals(actual = r.str2Tuple5().avg(), expected = 48)
    }
}
