// Autogenerated from KST: please remove this line if doing any edits by hand!

package io.kaitai.struct.spec

import io.kaitai.struct.typing.*
import io.kaitai.struct.testformats.ParamsPassStruct
import kotlin.test.*
import okio.FileSystem
import okio.Path.Companion.toPath
import okio.SYSTEM

class TestParamsPassStruct {
    val SRC_DIR = FileSystem.SYSTEM.canonicalize("../../../src/".toPath(true))

    @Test
    fun testParamsPassStruct() {
        val path = SRC_DIR.resolve("enum_negative.bin").toString()
        val r: ParamsPassStruct = ParamsPassStruct.fromFile(path)

        assertEquals(actual = r.first().foo(), expected = 255)
        assertEquals(actual = r.one().bar().qux(), expected = 1)
        assertEquals(actual = (r.one().foo() as ParamsPassStruct.Block) /* generic cast */.foo(), expected = 255)
        assertEquals(actual = (r.one().bar().foo() as ParamsPassStruct.Block) /* generic cast */.foo(), expected = 255)
    }
}
