// Autogenerated from KST: please remove this line if doing any edits by hand!

package io.kaitai.struct.spec

import io.kaitai.struct.typing.*
import io.kaitai.struct.testformats.StrLiterals2
import kotlin.test.*
import okio.FileSystem
import okio.Path.Companion.toPath
import okio.SYSTEM

class TestStrLiterals2 {
    val SRC_DIR = FileSystem.SYSTEM.canonicalize("../../../src/".toPath(true))

    @Test
    fun testStrLiterals2() {
        val path = SRC_DIR.resolve("fixed_struct.bin").toString()
        val r: StrLiterals2 = StrLiterals2.fromFile(path)

        assertEquals(actual = r.dollar1(), expected = "\$foo")
        assertEquals(actual = r.dollar2(), expected = "\${foo}")
        assertEquals(actual = r.hash(), expected = "#{foo}")
        assertEquals(actual = r.atSign(), expected = "@foo")
    }
}
