// Autogenerated from KST: please remove this line if doing any edits by hand!

package io.kaitai.struct.spec

import io.kaitai.struct.typing.*
import io.kaitai.struct.testformats.ParamsCall
import kotlin.test.*
import okio.FileSystem
import okio.Path.Companion.toPath
import okio.SYSTEM

class TestParamsCall {
    val SRC_DIR = FileSystem.SYSTEM.canonicalize("../../../src/".toPath(true))

    @Test
    fun testParamsCall() {
        val path = SRC_DIR.resolve("term_strz.bin").toString()
        val r: ParamsCall = ParamsCall.fromFile(path)

        assertEquals(actual = r.buf1().body(), expected = "foo|b")
        assertEquals(actual = r.buf2().body(), expected = "ar|ba")
        assertEquals(actual = r.buf2().trailer(), expected = 122)
    }
}
