// Autogenerated from KST: please remove this line if doing any edits by hand!

package io.kaitai.struct.spec

import io.kaitai.struct.typing.*
import io.kaitai.struct.testformats.ValidFailExpr
import kotlin.test.*
import io.kaitai.struct.KaitaiStream
import okio.FileSystem
import okio.Path.Companion.toPath
import okio.SYSTEM

class TestValidFailExpr {
    val SRC_DIR = FileSystem.SYSTEM.canonicalize("../../../src/".toPath(true))

    @Test
    fun testValidFailExpr() {
        assertFailsWith(KaitaiStream.ValidationExprError::class) {
            val path = SRC_DIR.resolve("nav_parent_switch.bin").toString()
            ValidFailExpr.fromFile(path)
        }
    }
}
