// Autogenerated from KST: please remove this line if doing any edits by hand!

package io.kaitai.struct.spec

import io.kaitai.struct.typing.*
import io.kaitai.struct.testformats.StrEncodingsUtf16
import kotlin.test.*
import okio.FileSystem
import okio.Path.Companion.toPath
import okio.SYSTEM

class TestStrEncodingsUtf16 {
    val SRC_DIR = FileSystem.SYSTEM.canonicalize("../../../src/".toPath(true))

    @Test
    fun testStrEncodingsUtf16() {
        val path = SRC_DIR.resolve("str_encodings_utf16.bin").toString()
        val r: StrEncodingsUtf16 = StrEncodingsUtf16.fromFile(path)

        assertEquals(actual = r.lenBe(), expected = 12)
        assertEquals(actual = r.beBomRemoved().bom(), expected = 65279)
        assertEquals(actual = r.beBomRemoved().str(), expected = "\u3053\u3093\u306b\u3061\u306f")
        assertEquals(actual = r.lenLe(), expected = 12)
        assertEquals(actual = r.leBomRemoved().bom(), expected = 65279)
        assertEquals(actual = r.leBomRemoved().str(), expected = "\u3053\u3093\u306b\u3061\u306f")
    }
}
