// Autogenerated from KST: please remove this line if doing any edits by hand!

package io.kaitai.struct.spec

import io.kaitai.struct.typing.*
import io.kaitai.struct.testformats.MultipleUse
import kotlin.test.*
import okio.FileSystem
import okio.Path.Companion.toPath
import okio.SYSTEM

class TestMultipleUse {
    val SRC_DIR = FileSystem.SYSTEM.canonicalize("../../../src/".toPath(true))

    @Test
    fun testMultipleUse() {
        val path = SRC_DIR.resolve("position_abs.bin").toString()
        val r: MultipleUse = MultipleUse.fromFile(path)

        assertEquals(actual = r.t1().firstUse().value(), expected = 32)
        assertEquals(actual = r.t2().secondUse().value(), expected = 32)
    }
}
