// Autogenerated from KST: please remove this line if doing any edits by hand!

package io.kaitai.struct.spec

import io.kaitai.struct.typing.*
import io.kaitai.struct.testformats.SwitchManualEnumInvalidElse
import kotlin.test.*
import okio.FileSystem
import okio.Path.Companion.toPath
import okio.SYSTEM

class TestSwitchManualEnumInvalidElse {
    val SRC_DIR = FileSystem.SYSTEM.canonicalize("../../../src/".toPath(true))

    @Test
    fun testSwitchManualEnumInvalidElse() {
        val path = SRC_DIR.resolve("enum_negative.bin").toString()
        val r: SwitchManualEnumInvalidElse = SwitchManualEnumInvalidElse.fromFile(path)

        assertEquals(actual = r.opcodes().size, expected = 2)
        assertEquals(actual = r.opcodes()[0].code(), expected = 255)
        assertEquals(actual = (r.opcodes()[0].body() as SwitchManualEnumInvalidElse.Opcode.Defval) /* generic cast */.value(), expected = 123)
        assertEquals(actual = r.opcodes()[1].code(), expected = 1)
        assertEquals(actual = (r.opcodes()[1].body() as SwitchManualEnumInvalidElse.Opcode.Defval) /* generic cast */.value(), expected = 123)
    }
}
