// Autogenerated from KST: please remove this line if doing any edits by hand!

package io.kaitai.struct.spec

import io.kaitai.struct.typing.*
import io.kaitai.struct.testformats.UserType
import kotlin.test.*
import okio.FileSystem
import okio.Path.Companion.toPath
import okio.SYSTEM

class TestUserType {
    val SRC_DIR = FileSystem.SYSTEM.canonicalize("../../../src/".toPath(true))

    @Test
    fun testUserType() {
        val path = SRC_DIR.resolve("repeat_until_s4.bin").toString()
        val r: UserType = UserType.fromFile(path)

        assertEquals(actual = r.one().width(), expected = 66)
        assertEquals(actual = r.one().height(), expected = 4919)
    }
}
