// Autogenerated from KST: please remove this line if doing any edits by hand!

package io.kaitai.struct.spec

import io.kaitai.struct.typing.*
import io.kaitai.struct.testformats.ParamsEnum
import kotlin.test.*
import okio.FileSystem
import okio.Path.Companion.toPath
import okio.SYSTEM

class TestParamsEnum {
    val SRC_DIR = FileSystem.SYSTEM.canonicalize("../../../src/".toPath(true))

    @Test
    fun testParamsEnum() {
        val path = SRC_DIR.resolve("enum_0.bin").toString()
        val r: ParamsEnum = ParamsEnum.fromFile(path)

        assertEquals(actual = r.one(), expected = ParamsEnum.Animal.CAT)
        assertEquals(actual = r.invokeWithParam().isCat(), expected = true)
    }
}
