// Autogenerated from KST: please remove this line if doing any edits by hand!

package io.kaitai.struct.spec

import io.kaitai.struct.typing.*
import io.kaitai.struct.testformats.FloatingPoints
import kotlin.test.*
import okio.FileSystem
import okio.Path.Companion.toPath
import okio.SYSTEM

class TestFloatingPoints {
    val SRC_DIR = FileSystem.SYSTEM.canonicalize("../../../src/".toPath(true))

    @Test
    fun testFloatingPoints() {
        val path = SRC_DIR.resolve("floating_points.bin").toString()
        val r: FloatingPoints = FloatingPoints.fromFile(path)

        assertEquals(r.singleValue(), 0.5.toFloat(), 1e-6)
        assertEquals(r.singleValueBe(), 0.5.toFloat(), 1e-6)
        assertEquals(r.doubleValue(), 0.25, 1e-6)
        assertEquals(r.doubleValueBe(), 0.25, 1e-6)
        assertEquals(r.approximateValue(), 1.2345, 1e-6)
        assertEquals(r.singleValuePlusInt(), 1.5, 1e-6)
        assertEquals(r.singleValuePlusFloat(), 1.0, 1e-6)
        assertEquals(r.doubleValuePlusFloat(), 0.3, 1e-6)
    }
}
