// Autogenerated from KST: please remove this line if doing any edits by hand!

package io.kaitai.struct.spec

import io.kaitai.struct.typing.*
import io.kaitai.struct.testformats.StrPadTerm
import kotlin.test.*
import okio.FileSystem
import okio.Path.Companion.toPath
import okio.SYSTEM

class TestStrPadTerm {
    val SRC_DIR = FileSystem.SYSTEM.canonicalize("../../../src/".toPath(true))

    @Test
    fun testStrPadTerm() {
        val path = SRC_DIR.resolve("str_pad_term.bin").toString()
        val r: StrPadTerm = StrPadTerm.fromFile(path)

        assertEquals(actual = r.strPad(), expected = "str1")
        assertEquals(actual = r.strTerm(), expected = "str2foo")
        assertEquals(actual = r.strTermAndPad(), expected = "str+++3bar+++")
        assertEquals(actual = r.strTermInclude(), expected = "str4baz@")
    }
}
