// Autogenerated from KST: please remove this line if doing any edits by hand!

package io.kaitai.struct.spec

import io.kaitai.struct.typing.*
import io.kaitai.struct.testformats.ExprToITrailing
import kotlin.test.*
import okio.FileSystem
import okio.Path.Companion.toPath
import okio.SYSTEM
import io.kaitai.struct.KaitaiStream

class TestExprToITrailing {
    val SRC_DIR = FileSystem.SYSTEM.canonicalize("../../../src/".toPath(true))

    @Test
    fun testExprToITrailing() {
        val path = SRC_DIR.resolve("term_strz.bin").toString()
        val r: ExprToITrailing = ExprToITrailing.fromFile(path)

        assertFailsWith(NumberFormatException::class) {
            r.toIR10()
        }
        assertEquals(actual = r.toIR16(), expected = 152517308)
        assertFailsWith(NumberFormatException::class) {
            r.toIGarbage()
        }
    }
}
