// Autogenerated from KST: please remove this line if doing any edits by hand!

package io.kaitai.struct.spec

import io.kaitai.struct.typing.*
import io.kaitai.struct.testformats.RepeatNStruct
import kotlin.test.*
import okio.FileSystem
import okio.Path.Companion.toPath
import okio.SYSTEM

class TestRepeatNStruct {
    val SRC_DIR = FileSystem.SYSTEM.canonicalize("../../../src/".toPath(true))

    @Test
    fun testRepeatNStruct() {
        val path = SRC_DIR.resolve("repeat_n_struct.bin").toString()
        val r: RepeatNStruct = RepeatNStruct.fromFile(path)

        assertEquals(actual = r.chunks().size, expected = 2)
        assertEquals(actual = r.chunks()[0].offset(), expected = 16)
        assertEquals(actual = r.chunks()[0].len(), expected = 8312)
        assertEquals(actual = r.chunks()[1].offset(), expected = 8328)
        assertEquals(actual = r.chunks()[1].len(), expected = 15)
    }
}
