// Autogenerated from KST: please remove this line if doing any edits by hand!

package io.kaitai.struct.spec

import io.kaitai.struct.typing.*
import io.kaitai.struct.testformats.Imports0
import kotlin.test.*
import okio.FileSystem
import okio.Path.Companion.toPath
import okio.SYSTEM

class TestImports0 {
    val SRC_DIR = FileSystem.SYSTEM.canonicalize("../../../src/".toPath(true))

    @Test
    fun testImports0() {
        val path = SRC_DIR.resolve("fixed_struct.bin").toString()
        val r: Imports0 = Imports0.fromFile(path)

        assertEquals(actual = r.two(), expected = 80)
        assertEquals(actual = r.hw().one(), expected = 65)
        assertEquals(actual = r.hwOne(), expected = 65)
    }
}
