// Autogenerated from KST: please remove this line if doing any edits by hand!

package io.kaitai.struct.spec

import io.kaitai.struct.typing.*
import io.kaitai.struct.testformats.NavParentSwitch
import kotlin.test.*
import okio.FileSystem
import okio.Path.Companion.toPath
import okio.SYSTEM

class TestNavParentSwitch {
    val SRC_DIR = FileSystem.SYSTEM.canonicalize("../../../src/".toPath(true))

    @Test
    fun testNavParentSwitch() {
        val path = SRC_DIR.resolve("nav_parent_switch.bin").toString()
        val r: NavParentSwitch = NavParentSwitch.fromFile(path)

        assertEquals(actual = r.category(), expected = 1)
        assertEquals(actual = (r.content() as NavParentSwitch.Element1) /* generic cast */.foo(), expected = 66)
        assertEquals(actual = (r.content() as NavParentSwitch.Element1) /* generic cast */.subelement().bar(), expected = 255)
    }
}
