// Autogenerated from KST: please remove this line if doing any edits by hand!

package io.kaitai.struct.spec

import io.kaitai.struct.typing.*
import io.kaitai.struct.testformats.RepeatNStrz
import kotlin.test.*
import okio.FileSystem
import okio.Path.Companion.toPath
import okio.SYSTEM

class TestRepeatNStrz {
    val SRC_DIR = FileSystem.SYSTEM.canonicalize("../../../src/".toPath(true))

    @Test
    fun testRepeatNStrz() {
        val path = SRC_DIR.resolve("repeat_n_strz.bin").toString()
        val r: RepeatNStrz = RepeatNStrz.fromFile(path)

        assertEquals(actual = r.qty(), expected = 2)
        assertContentEquals(actual = r.lines(), expected = arrayListOf("foo", "bar"))
    }
}
