// Autogenerated from KST: please remove this line if doing any edits by hand!

package io.kaitai.struct.spec

import io.kaitai.struct.typing.*
import io.kaitai.struct.testformats.IoLocalVar
import kotlin.test.*
import okio.FileSystem
import okio.Path.Companion.toPath
import okio.SYSTEM

class TestIoLocalVar {
    val SRC_DIR = FileSystem.SYSTEM.canonicalize("../../../src/".toPath(true))

    @Test
    fun testIoLocalVar() {
        val path = SRC_DIR.resolve("full256.bin").toString()
        val r: IoLocalVar = IoLocalVar.fromFile(path)

        assertEquals(actual = r.skip(), expected = byteArrayOf(0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19))
        assertEquals(actual = r.followup(), expected = 20)
    }
}
