// Autogenerated from KST: please remove this line if doing any edits by hand!

package io.kaitai.struct.spec

import io.kaitai.struct.typing.*
import io.kaitai.struct.testformats.RecursiveOne
import kotlin.test.*
import okio.FileSystem
import okio.Path.Companion.toPath
import okio.SYSTEM

class TestRecursiveOne {
    val SRC_DIR = FileSystem.SYSTEM.canonicalize("../../../src/".toPath(true))

    @Test
    fun testRecursiveOne() {
        val path = SRC_DIR.resolve("fixed_struct.bin").toString()
        val r: RecursiveOne = RecursiveOne.fromFile(path)

        assertEquals(actual = r.one(), expected = 80)
        assertEquals(actual = (r.next() as RecursiveOne) /* generic cast */.one(), expected = 65)
        assertEquals(actual = ((r.next() as RecursiveOne) /* generic cast */.next() as RecursiveOne) /* generic cast */.one(), expected = 67)
        assertEquals(actual = (((r.next() as RecursiveOne) /* generic cast */.next() as RecursiveOne) /* generic cast */.next() as RecursiveOne.Fini) /* generic cast */.finisher(), expected = 11595)
    }
}
