// Autogenerated from KST: please remove this line if doing any edits by hand!

package io.kaitai.struct.spec

import io.kaitai.struct.typing.*
import io.kaitai.struct.testformats.ValidFailRangeFloat
import kotlin.test.*
import io.kaitai.struct.KaitaiStream
import okio.FileSystem
import okio.Path.Companion.toPath
import okio.SYSTEM

class TestValidFailRangeFloat {
    val SRC_DIR = FileSystem.SYSTEM.canonicalize("../../../src/".toPath(true))

    @Test
    fun testValidFailRangeFloat() {
        assertFailsWith(KaitaiStream.ValidationGreaterThanError::class) {
            val path = SRC_DIR.resolve("floating_points.bin").toString()
            ValidFailRangeFloat.fromFile(path)
        }
    }
}
