// Autogenerated from KST: please remove this line if doing any edits by hand!

package io.kaitai.struct.spec

import io.kaitai.struct.typing.*
import io.kaitai.struct.testformats.ParamsPassArrayInt
import kotlin.test.*
import okio.FileSystem
import okio.Path.Companion.toPath
import okio.SYSTEM

class TestParamsPassArrayInt {
    val SRC_DIR = FileSystem.SYSTEM.canonicalize("../../../src/".toPath(true))

    @Test
    fun testParamsPassArrayInt() {
        val path = SRC_DIR.resolve("position_to_end.bin").toString()
        val r: ParamsPassArrayInt = ParamsPassArrayInt.fromFile(path)

        assertEquals(actual = r.passInts().nums().size, expected = 3)
        assertEquals(actual = r.passInts().nums()[0], expected = 513)
        assertEquals(actual = r.passInts().nums()[1], expected = 1027)
        assertEquals(actual = r.passInts().nums()[2], expected = 1541)
        assertEquals(actual = r.passIntsCalc().nums().size, expected = 2)
        assertEquals(actual = r.passIntsCalc().nums()[0], expected = 27643)
        assertEquals(actual = r.passIntsCalc().nums()[1], expected = 7)
    }
}
