// Autogenerated from KST: please remove this line if doing any edits by hand!

package io.kaitai.struct.spec

import io.kaitai.struct.typing.*
import io.kaitai.struct.testformats.DebugSwitchUser
import kotlin.test.*
import okio.FileSystem
import okio.Path.Companion.toPath
import okio.SYSTEM

class TestDebugSwitchUser {
    val SRC_DIR = FileSystem.SYSTEM.canonicalize("../../../src/".toPath(true))

    @Test
    fun testDebugSwitchUser() {
        val path = SRC_DIR.resolve("nav_parent_switch.bin").toString()
        val r: DebugSwitchUser = DebugSwitchUser.fromFile(path)
        r._read()

        assertEquals(actual = r.code(), expected = 1)
        assertEquals(actual = (r.data() as DebugSwitchUser.One) /* generic cast */.`val`(), expected = -190)
    }
}
