// Autogenerated from KST: please remove this line if doing any edits by hand!

package io.kaitai.struct.spec

import io.kaitai.struct.typing.*
import io.kaitai.struct.testformats.ParamsPassBool
import kotlin.test.*
import okio.FileSystem
import okio.Path.Companion.toPath
import okio.SYSTEM

class TestParamsPassBool {
    val SRC_DIR = FileSystem.SYSTEM.canonicalize("../../../src/".toPath(true))

    @Test
    fun testParamsPassBool() {
        val path = SRC_DIR.resolve("term_strz.bin").toString()
        val r: ParamsPassBool = ParamsPassBool.fromFile(path)

        assertEquals(actual = r.sFalse(), expected = false)
        assertEquals(actual = r.sTrue(), expected = true)
        assertEquals(actual = r.seqB1().arg(), expected = true)
        assertEquals(actual = r.seqB1().foo().size, expected = 1)
        assertEquals(actual = r.seqBool().arg(), expected = false)
        assertEquals(actual = r.seqBool().foo().size, expected = 2)
        assertEquals(actual = r.literalB1().arg(), expected = false)
        assertEquals(actual = r.literalB1().foo().size, expected = 2)
        assertEquals(actual = r.literalBool().arg(), expected = true)
        assertEquals(actual = r.literalBool().foo().size, expected = 1)
        assertEquals(actual = r.instB1().arg(), expected = true)
        assertEquals(actual = r.instB1().foo().size, expected = 1)
        assertEquals(actual = r.instBool().arg(), expected = false)
        assertEquals(actual = r.instBool().foo().size, expected = 2)
    }
}
