// Autogenerated from KST: please remove this line if doing any edits by hand!

package io.kaitai.struct.spec

import io.kaitai.struct.typing.*
import io.kaitai.struct.testformats.Expr3
import kotlin.test.*
import okio.FileSystem
import okio.Path.Companion.toPath
import okio.SYSTEM

class TestExpr3 {
    val SRC_DIR = FileSystem.SYSTEM.canonicalize("../../../src/".toPath(true))

    @Test
    fun testExpr3() {
        val path = SRC_DIR.resolve("fixed_struct.bin").toString()
        val r: Expr3 = Expr3.fromFile(path)

        assertEquals(actual = r.one(), expected = 80)
        assertEquals(actual = r.two(), expected = "ACK")
        assertEquals(actual = r.three(), expected = "@ACK")
        assertEquals(actual = r.four(), expected = "_ACK_")
        assertEquals(actual = r.isStrEq(), expected = true)
        assertEquals(actual = r.isStrNe(), expected = false)
        assertEquals(actual = r.isStrLt(), expected = true)
        assertEquals(actual = r.isStrGt(), expected = false)
        assertEquals(actual = r.isStrLe(), expected = true)
        assertEquals(actual = r.isStrGe(), expected = false)
        assertEquals(actual = r.isStrLt2(), expected = true)
        assertEquals(actual = r.testNot(), expected = true)
    }
}
