// Autogenerated from KST: please remove this line if doing any edits by hand!

package io.kaitai.struct.spec

import io.kaitai.struct.typing.*
import io.kaitai.struct.testformats.ExprIntDiv
import kotlin.test.*
import okio.FileSystem
import okio.Path.Companion.toPath
import okio.SYSTEM

class TestExprIntDiv {
    val SRC_DIR = FileSystem.SYSTEM.canonicalize("../../../src/".toPath(true))

    @Test
    fun testExprIntDiv() {
        val path = SRC_DIR.resolve("fixed_struct.bin").toString()
        val r: ExprIntDiv = ExprIntDiv.fromFile(path)

        assertEquals(actual = r.intU(), expected = 1262698832)
        assertEquals(actual = r.intS(), expected = -52947)
        assertEquals(actual = r.divPosConst(), expected = 756)
        assertEquals(actual = r.divNegConst(), expected = -757)
        assertEquals(actual = r.divPosSeq(), expected = 97130679)
        assertEquals(actual = r.divNegSeq(), expected = -4073)
    }
}
