// Autogenerated from KST: please remove this line if doing any edits by hand!

package io.kaitai.struct.spec

import io.kaitai.struct.typing.*
import io.kaitai.struct.testformats.RepeatEosStruct
import kotlin.test.*
import okio.FileSystem
import okio.Path.Companion.toPath
import okio.SYSTEM

class TestRepeatEosStruct {
    val SRC_DIR = FileSystem.SYSTEM.canonicalize("../../../src/".toPath(true))

    @Test
    fun testRepeatEosStruct() {
        val path = SRC_DIR.resolve("repeat_eos_struct.bin").toString()
        val r: RepeatEosStruct = RepeatEosStruct.fromFile(path)

        assertEquals(actual = r.chunks().size, expected = 2)
        assertEquals(actual = r.chunks()[0].offset(), expected = 0)
        assertEquals(actual = r.chunks()[0].len(), expected = 66)
        assertEquals(actual = r.chunks()[1].offset(), expected = 66)
        assertEquals(actual = r.chunks()[1].len(), expected = 2069)
    }
}
