// Autogenerated from KST: please remove this line if doing any edits by hand!

package io.kaitai.struct.spec

import io.kaitai.struct.typing.*
import io.kaitai.struct.testformats.EnumIntRangeU
import kotlin.test.*
import okio.FileSystem
import okio.Path.Companion.toPath
import okio.SYSTEM

class TestEnumIntRangeU {
    val SRC_DIR = FileSystem.SYSTEM.canonicalize("../../../src/".toPath(true))

    @Test
    fun testEnumIntRangeU() {
        val path = SRC_DIR.resolve("enum_int_range_u.bin").toString()
        val r: EnumIntRangeU = EnumIntRangeU.fromFile(path)

        assertEquals(actual = r.f1(), expected = EnumIntRangeU.Constants.ZERO)
        assertEquals(actual = r.f2(), expected = EnumIntRangeU.Constants.INT_MAX)
    }
}
