// Autogenerated from KST: please remove this line if doing any edits by hand!

package io.kaitai.struct.spec

import io.kaitai.struct.typing.*
import io.kaitai.struct.testformats.ParamsCallExtraParens
import kotlin.test.*
import okio.FileSystem
import okio.Path.Companion.toPath
import okio.SYSTEM

class TestParamsCallExtraParens {
    val SRC_DIR = FileSystem.SYSTEM.canonicalize("../../../src/".toPath(true))

    @Test
    fun testParamsCallExtraParens() {
        val path = SRC_DIR.resolve("term_strz.bin").toString()
        val r: ParamsCallExtraParens = ParamsCallExtraParens.fromFile(path)

        assertEquals(actual = r.buf1().body(), expected = "foo|b")
    }
}
