// Autogenerated from KST: please remove this line if doing any edits by hand!

package io.kaitai.struct.spec

import io.kaitai.struct.typing.*
import io.kaitai.struct.testformats.RepeatEosU4
import kotlin.test.*
import okio.FileSystem
import okio.Path.Companion.toPath
import okio.SYSTEM

class TestRepeatEosU4 {
    val SRC_DIR = FileSystem.SYSTEM.canonicalize("../../../src/".toPath(true))

    @Test
    fun testRepeatEosU4() {
        val path = SRC_DIR.resolve("repeat_eos_struct.bin").toString()
        val r: RepeatEosU4 = RepeatEosU4.fromFile(path)

        assertContentEquals(actual = r.numbers(), expected = arrayListOf(0, 66, 66, 2069))
    }
}
