// Autogenerated from KST: please remove this line if doing any edits by hand!

package io.kaitai.struct.spec

import io.kaitai.struct.typing.*
import io.kaitai.struct.testformats.CastNested
import kotlin.test.*
import okio.FileSystem
import okio.Path.Companion.toPath
import okio.SYSTEM

class TestCastNested {
    val SRC_DIR = FileSystem.SYSTEM.canonicalize("../../../src/".toPath(true))

    @Test
    fun testCastNested() {
        val path = SRC_DIR.resolve("switch_opcodes.bin").toString()
        val r: CastNested = CastNested.fromFile(path)

        assertEquals(actual = r.opcodes0Str().value(), expected = "foobar")
        assertEquals(actual = r.opcodes0StrValue(), expected = "foobar")
        assertEquals(actual = r.opcodes1Int().value(), expected = 66)
        assertEquals(actual = r.opcodes1IntValue(), expected = 66)
    }
}
