// Autogenerated from KST: please remove this line if doing any edits by hand!

package io.kaitai.struct.spec

import io.kaitai.struct.typing.*
import io.kaitai.struct.testformats.NavParentOverride
import kotlin.test.*
import okio.FileSystem
import okio.Path.Companion.toPath
import okio.SYSTEM

class TestNavParentOverride {
    val SRC_DIR = FileSystem.SYSTEM.canonicalize("../../../src/".toPath(true))

    @Test
    fun testNavParentOverride() {
        val path = SRC_DIR.resolve("nav_parent_codes.bin").toString()
        val r: NavParentOverride = NavParentOverride.fromFile(path)

        assertEquals(actual = r.childSize(), expected = 3)
        assertEquals(actual = r.child1().data(), expected = byteArrayOf(73, 49, 50))
        assertEquals(actual = r.mediator2().child2().data(), expected = byteArrayOf(51, 66, 98))
    }
}
