// Autogenerated from KST: please remove this line if doing any edits by hand!

package io.kaitai.struct.spec

import io.kaitai.struct.typing.*
import io.kaitai.struct.testformats.InstanceStdArray
import kotlin.test.*
import okio.FileSystem
import okio.Path.Companion.toPath
import okio.SYSTEM

class TestInstanceStdArray {
    val SRC_DIR = FileSystem.SYSTEM.canonicalize("../../../src/".toPath(true))

    @Test
    fun testInstanceStdArray() {
        val path = SRC_DIR.resolve("instance_std_array.bin").toString()
        val r: InstanceStdArray = InstanceStdArray.fromFile(path)

        assertEquals(actual = r.ofs(), expected = 16)
        assertEquals(actual = r.qtyEntries(), expected = 3)
        assertEquals(actual = r.entrySize(), expected = 4)
        assertEquals(actual = r.entries().size, expected = 3)
        assertEquals(actual = r.entries()[0], expected = byteArrayOf(17, 17, 17, 17))
        assertEquals(actual = r.entries()[1], expected = byteArrayOf(34, 34, 34, 34))
        assertEquals(actual = r.entries()[2], expected = byteArrayOf(51, 51, 51, 51))
    }
}
