// Autogenerated from KST: please remove this line if doing any edits by hand!

package io.kaitai.struct.spec

import io.kaitai.struct.typing.*
import io.kaitai.struct.testformats.NavRoot
import kotlin.test.*
import okio.FileSystem
import okio.Path.Companion.toPath
import okio.SYSTEM

class TestNavRoot {
    val SRC_DIR = FileSystem.SYSTEM.canonicalize("../../../src/".toPath(true))

    @Test
    fun testNavRoot() {
        val path = SRC_DIR.resolve("nav.bin").toString()
        val r: NavRoot = NavRoot.fromFile(path)

        assertEquals(actual = r.header().qtyEntries(), expected = 2)
        assertEquals(actual = r.header().filenameLen(), expected = 8)
        assertEquals(actual = r.index().entries().size, expected = 2)
        assertEquals(actual = r.index().entries()[0].filename(), expected = "FIRST___")
        assertEquals(actual = r.index().entries()[1].filename(), expected = "SECOND__")
    }
}
