// Autogenerated from KST: please remove this line if doing any edits by hand!

package io.kaitai.struct.spec

import io.kaitai.struct.typing.*
import io.kaitai.struct.testformats.IfStruct
import kotlin.test.*
import okio.FileSystem
import okio.Path.Companion.toPath
import okio.SYSTEM

class TestIfStruct {
    val SRC_DIR = FileSystem.SYSTEM.canonicalize("../../../src/".toPath(true))

    @Test
    fun testIfStruct() {
        val path = SRC_DIR.resolve("if_struct.bin").toString()
        val r: IfStruct = IfStruct.fromFile(path)

        assertEquals(actual = r.op1().opcode(), expected = 83)
        assertEquals(actual = r.op1().argStr().str(), expected = "foo")
        assertEquals(actual = r.op2().opcode(), expected = 84)
        assertEquals(actual = r.op2().argTuple().num1(), expected = 66)
        assertEquals(actual = r.op2().argTuple().num2(), expected = 67)
        assertEquals(actual = r.op3().opcode(), expected = 83)
        assertEquals(actual = r.op3().argStr().str(), expected = "bar")
    }
}
