// Autogenerated from KST: please remove this line if doing any edits by hand!

package io.kaitai.struct.spec

import io.kaitai.struct.typing.*
import io.kaitai.struct.testformats.EnumDeep
import kotlin.test.*
import okio.FileSystem
import okio.Path.Companion.toPath
import okio.SYSTEM

class TestEnumDeep {
    val SRC_DIR = FileSystem.SYSTEM.canonicalize("../../../src/".toPath(true))

    @Test
    fun testEnumDeep() {
        val path = SRC_DIR.resolve("enum_0.bin").toString()
        val r: EnumDeep = EnumDeep.fromFile(path)

        assertEquals(actual = r.pet1(), expected = EnumDeep.Container1.Animal.CAT)
        assertEquals(actual = r.pet2(), expected = EnumDeep.Container1.Container2.Animal.HARE)
    }
}
