// Autogenerated from KST: please remove this line if doing any edits by hand!

package io.kaitai.struct.spec

import io.kaitai.struct.typing.*
import io.kaitai.struct.testformats.ExprOpsParens
import kotlin.test.*
import okio.FileSystem
import okio.Path.Companion.toPath
import okio.SYSTEM

class TestExprOpsParens {
    val SRC_DIR = FileSystem.SYSTEM.canonicalize("../../../src/".toPath(true))

    @Test
    fun testExprOpsParens() {
        val path = SRC_DIR.resolve("enum_negative.bin").toString()
        val r: ExprOpsParens = ExprOpsParens.fromFile(path)

        assertEquals(actual = r.iSumToStr(), expected = "29")
        assertEquals(actual = r.fSumToInt(), expected = 9)
        assertEquals(actual = r.strConcatLen(), expected = 10)
        assertEquals(actual = r.strConcatRev(), expected = "9876543210")
        assertEquals(actual = r.strConcatSubstr2To7(), expected = "23456")
        assertEquals(actual = r.strConcatToI(), expected = 123456789)
        assertEquals(actual = r.boolEq(), expected = 0)
        assertEquals(actual = r.boolAnd(), expected = 0)
        assertEquals(actual = r.boolOr(), expected = 1)
    }
}
