// Autogenerated from KST: please remove this line if doing any edits by hand!

package io.kaitai.struct.spec

import io.kaitai.struct.typing.*
import io.kaitai.struct.testformats.BitsShiftByB32Le
import kotlin.test.*
import okio.FileSystem
import okio.Path.Companion.toPath
import okio.SYSTEM

class TestBitsShiftByB32Le {
    val SRC_DIR = FileSystem.SYSTEM.canonicalize("../../../src/".toPath(true))

    @Test
    fun testBitsShiftByB32Le() {
        val path = SRC_DIR.resolve("bits_shift_by_b32_le.bin").toString()
        val r: BitsShiftByB32Le = BitsShiftByB32Le.fromFile(path)

        assertEquals(actual = r.a(), expected = 4294967295)
        assertEquals(actual = r.b(), expected = 0)
    }
}
