// Autogenerated from KST: please remove this line if doing any edits by hand!

package io.kaitai.struct.spec

import io.kaitai.struct.typing.*
import io.kaitai.struct.testformats.ProcessXorConst
import kotlin.test.*
import okio.FileSystem
import okio.Path.Companion.toPath
import okio.SYSTEM

class TestProcessXorConst {
    val SRC_DIR = FileSystem.SYSTEM.canonicalize("../../../src/".toPath(true))

    @Test
    fun testProcessXorConst() {
        val path = SRC_DIR.resolve("process_xor_1.bin").toString()
        val r: ProcessXorConst = ProcessXorConst.fromFile(path)

        assertEquals(actual = r.key(), expected = 255)
        assertEquals(actual = r.buf(), expected = byteArrayOf(102, 111, 111, 32, 98, 97, 114))
    }
}
