// Autogenerated from KST: please remove this line if doing any edits by hand!

package io.kaitai.struct.spec

import io.kaitai.struct.typing.*
import io.kaitai.struct.testformats.BitsSeqEndianCombo
import kotlin.test.*
import okio.FileSystem
import okio.Path.Companion.toPath
import okio.SYSTEM

class TestBitsSeqEndianCombo {
    val SRC_DIR = FileSystem.SYSTEM.canonicalize("../../../src/".toPath(true))

    @Test
    fun testBitsSeqEndianCombo() {
        val path = SRC_DIR.resolve("process_xor_4.bin").toString()
        val r: BitsSeqEndianCombo = BitsSeqEndianCombo.fromFile(path)

        assertEquals(actual = r.be1(), expected = 59)
        assertEquals(actual = r.be2(), expected = 187)
        assertEquals(actual = r.le3(), expected = 163)
        assertEquals(actual = r.be4(), expected = 20)
        assertEquals(actual = r.le5(), expected = 10)
        assertEquals(actual = r.le6(), expected = 36)
        assertEquals(actual = r.le7(), expected = 26)
        assertEquals(actual = r.be8(), expected = true)
    }
}
