// Autogenerated from KST: please remove this line if doing any edits by hand!

package io.kaitai.struct.spec

import io.kaitai.struct.typing.*
import io.kaitai.struct.testformats.ParamsPassArrayStruct
import kotlin.test.*
import okio.FileSystem
import okio.Path.Companion.toPath
import okio.SYSTEM

class TestParamsPassArrayStruct {
    val SRC_DIR = FileSystem.SYSTEM.canonicalize("../../../src/".toPath(true))

    @Test
    fun testParamsPassArrayStruct() {
        val path = SRC_DIR.resolve("position_to_end.bin").toString()
        val r: ParamsPassArrayStruct = ParamsPassArrayStruct.fromFile(path)

        assertEquals(actual = r.passStructs().structs().size, expected = 2)
        assertEquals(actual = (r.passStructs().structs()[0] as ParamsPassArrayStruct.Foo) /* generic cast */.f(), expected = 1)
        assertEquals(actual = (r.passStructs().structs()[1] as ParamsPassArrayStruct.Bar) /* generic cast */.b(), expected = 2)
    }
}
