// Autogenerated from KST: please remove this line if doing any edits by hand!

package io.kaitai.struct.spec

import io.kaitai.struct.typing.*
import io.kaitai.struct.testformats.FloatToI
import kotlin.test.*
import okio.FileSystem
import okio.Path.Companion.toPath
import okio.SYSTEM

class TestFloatToI {
    val SRC_DIR = FileSystem.SYSTEM.canonicalize("../../../src/".toPath(true))

    @Test
    fun testFloatToI() {
        val path = SRC_DIR.resolve("floating_points.bin").toString()
        val r: FloatToI = FloatToI.fromFile(path)

        assertEquals(r.singleValue(), 0.5, 1e-6)
        assertEquals(r.doubleValue(), 0.25, 1e-6)
        assertEquals(actual = r.singleI(), expected = 0)
        assertEquals(actual = r.doubleI(), expected = 0)
        assertEquals(actual = r.float1I(), expected = 1)
        assertEquals(actual = r.float2I(), expected = 1)
        assertEquals(actual = r.float3I(), expected = 1)
        assertEquals(actual = r.float4I(), expected = -2)
    }
}
