// Autogenerated from KST: please remove this line if doing any edits by hand!

package io.kaitai.struct.spec

import io.kaitai.struct.typing.*
import io.kaitai.struct.testformats.ImportsCastToImported2
import kotlin.test.*
import okio.FileSystem
import okio.Path.Companion.toPath
import okio.SYSTEM

class TestImportsCastToImported2 {
    val SRC_DIR = FileSystem.SYSTEM.canonicalize("../../../src/".toPath(true))

    @Test
    fun testImportsCastToImported2() {
        val path = SRC_DIR.resolve("process_xor_4.bin").toString()
        val r: ImportsCastToImported2 = ImportsCastToImported2.fromFile(path)

        assertEquals(actual = r.hw().one(), expected = 236)
        assertEquals(actual = r.two().hw().one(), expected = 236)
    }
}
