// Autogenerated from KST: please remove this line if doing any edits by hand!

package io.kaitai.struct.spec

import io.kaitai.struct.typing.*
import io.kaitai.struct.testformats.BufferedStruct
import kotlin.test.*
import okio.FileSystem
import okio.Path.Companion.toPath
import okio.SYSTEM

class TestBufferedStruct {
    val SRC_DIR = FileSystem.SYSTEM.canonicalize("../../../src/".toPath(true))

    @Test
    fun testBufferedStruct() {
        val path = SRC_DIR.resolve("buffered_struct.bin").toString()
        val r: BufferedStruct = BufferedStruct.fromFile(path)

        assertEquals(actual = r.len1(), expected = 16)
        assertEquals(actual = r.block1().number1(), expected = 66)
        assertEquals(actual = r.block1().number2(), expected = 67)
        assertEquals(actual = r.len2(), expected = 8)
        assertEquals(actual = r.block2().number1(), expected = 68)
        assertEquals(actual = r.block2().number2(), expected = 69)
        assertEquals(actual = r.finisher(), expected = 238)
    }
}
