// Autogenerated from KST: please remove this line if doing any edits by hand!

package io.kaitai.struct.spec

import io.kaitai.struct.typing.*
import io.kaitai.struct.testformats.ImportsRel1
import kotlin.test.*
import okio.FileSystem
import okio.Path.Companion.toPath
import okio.SYSTEM

class TestImportsRel1 {
    val SRC_DIR = FileSystem.SYSTEM.canonicalize("../../../src/".toPath(true))

    @Test
    fun testImportsRel1() {
        val path = SRC_DIR.resolve("fixed_struct.bin").toString()
        val r: ImportsRel1 = ImportsRel1.fromFile(path)

        assertEquals(actual = r.one(), expected = 80)
        assertEquals(actual = r.two().one(), expected = 65)
        assertEquals(actual = r.two().two().one(), expected = 67)
    }
}
