// Autogenerated from KST: please remove this line if doing any edits by hand!

package io.kaitai.struct.spec

import io.kaitai.struct.typing.*
import io.kaitai.struct.testformats.NestedSameName
import kotlin.test.*
import okio.FileSystem
import okio.Path.Companion.toPath
import okio.SYSTEM

class TestNestedSameName {
    val SRC_DIR = FileSystem.SYSTEM.canonicalize("../../../src/".toPath(true))

    @Test
    fun testNestedSameName() {
        val path = SRC_DIR.resolve("repeat_n_struct.bin").toString()
        val r: NestedSameName = NestedSameName.fromFile(path)

        assertEquals(actual = r.mainData().mainSize(), expected = 2)
        assertEquals(actual = r.mainData().foo().data(), expected = byteArrayOf(16, 0, 0, 0))
    }
}
