// Autogenerated from KST: please remove this line if doing any edits by hand!

package io.kaitai.struct.spec

import io.kaitai.struct.typing.*
import io.kaitai.struct.testformats.DefaultEndianExprException
import kotlin.test.*
import io.kaitai.struct.KaitaiStream
import okio.FileSystem
import okio.Path.Companion.toPath
import okio.SYSTEM

class TestDefaultEndianExprException {
    val SRC_DIR = FileSystem.SYSTEM.canonicalize("../../../src/".toPath(true))

    @Test
    fun testDefaultEndianExprException() {
        assertFailsWith(KaitaiStream.UndecidedEndiannessError::class) {
            val path = SRC_DIR.resolve("endian_expr.bin").toString()
            DefaultEndianExprException.fromFile(path)
        }
    }
}
