// Autogenerated from KST: please remove this line if doing any edits by hand!

package io.kaitai.struct.spec

import io.kaitai.struct.typing.*
import io.kaitai.struct.testformats.BcdUserTypeLe
import kotlin.test.*
import okio.FileSystem
import okio.Path.Companion.toPath
import okio.SYSTEM

class TestBcdUserTypeLe {
    val SRC_DIR = FileSystem.SYSTEM.canonicalize("../../../src/".toPath(true))

    @Test
    fun testBcdUserTypeLe() {
        val path = SRC_DIR.resolve("bcd_user_type_le.bin").toString()
        val r: BcdUserTypeLe = BcdUserTypeLe.fromFile(path)

        assertEquals(actual = r.ltr().asInt(), expected = 12345678)
        assertEquals(actual = r.ltr().asStr(), expected = "12345678")
        assertEquals(actual = r.rtl().asInt(), expected = 87654321)
        assertEquals(actual = r.rtl().asStr(), expected = "87654321")
        assertEquals(actual = r.leadingZeroLtr().asInt(), expected = 123456)
        assertEquals(actual = r.leadingZeroLtr().asStr(), expected = "00123456")
    }
}
