// Autogenerated from KST: please remove this line if doing any edits by hand!

package io.kaitai.struct.spec

import io.kaitai.struct.typing.*
import io.kaitai.struct.testformats.ProcessCustom
import kotlin.test.*
import okio.FileSystem
import okio.Path.Companion.toPath
import okio.SYSTEM

class TestProcessCustom {
    val SRC_DIR = FileSystem.SYSTEM.canonicalize("../../../src/".toPath(true))

    @Test
    fun testProcessCustom() {
        val path = SRC_DIR.resolve("process_rotate.bin").toString()
        val r: ProcessCustom = ProcessCustom.fromFile(path)

        assertEquals(actual = r.buf1(), expected = byteArrayOf(16, -77, -108, -108, -12))
        assertEquals(actual = r.buf2(), expected = byteArrayOf(95, -70, 123, -109, 99, 35, 95))
        assertEquals(actual = r.buf3(), expected = byteArrayOf(41, 51, -79, 56, -79))
    }
}
