// Autogenerated from KST: please remove this line if doing any edits by hand!

package io.kaitai.struct.spec

import io.kaitai.struct.typing.*
import io.kaitai.struct.testformats.NavParentSwitchCast
import kotlin.test.*
import okio.FileSystem
import okio.Path.Companion.toPath
import okio.SYSTEM

class TestNavParentSwitchCast {
    val SRC_DIR = FileSystem.SYSTEM.canonicalize("../../../src/".toPath(true))

    @Test
    fun testNavParentSwitchCast() {
        val path = SRC_DIR.resolve("switch_integers.bin").toString()
        val r: NavParentSwitchCast = NavParentSwitchCast.fromFile(path)

        assertEquals(actual = r.main().bufType(), expected = 1)
        assertEquals(actual = r.main().flag(), expected = 7)
        assertEquals(actual = (r.main().buf() as NavParentSwitchCast.Foo.One) /* generic cast */.branch().flag(), expected = 7)
    }
}
