// Autogenerated from KST: please remove this line if doing any edits by hand!

package io.kaitai.struct.spec

import io.kaitai.struct.typing.*
import io.kaitai.struct.testformats.Expr1
import kotlin.test.*
import okio.FileSystem
import okio.Path.Companion.toPath
import okio.SYSTEM

class TestExpr1 {
    val SRC_DIR = FileSystem.SYSTEM.canonicalize("../../../src/".toPath(true))

    @Test
    fun testExpr1() {
        val path = SRC_DIR.resolve("str_encodings.bin").toString()
        val r: Expr1 = Expr1.fromFile(path)

        assertEquals(actual = r.lenOf1(), expected = 10)
        assertEquals(actual = r.lenOf1Mod(), expected = 8)
        assertEquals(actual = r.str1(), expected = "Some ASC")
        assertEquals(actual = r.str1Len(), expected = 8)
    }
}
