// Autogenerated from KST: please remove this line if doing any edits by hand!

package io.kaitai.struct.spec

import io.kaitai.struct.typing.*
import io.kaitai.struct.testformats.TermBytes
import kotlin.test.*
import okio.FileSystem
import okio.Path.Companion.toPath
import okio.SYSTEM

class TestTermBytes {
    val SRC_DIR = FileSystem.SYSTEM.canonicalize("../../../src/".toPath(true))

    @Test
    fun testTermBytes() {
        val path = SRC_DIR.resolve("term_strz.bin").toString()
        val r: TermBytes = TermBytes.fromFile(path)

        assertEquals(actual = r.s1(), expected = byteArrayOf(102, 111, 111))
        assertEquals(actual = r.s2(), expected = byteArrayOf(98, 97, 114))
        assertEquals(actual = r.s3(), expected = byteArrayOf(124, 98, 97, 122, 64))
    }
}
