// Autogenerated from KST: please remove this line if doing any edits by hand!

package io.kaitai.struct.spec

import io.kaitai.struct.typing.*
import io.kaitai.struct.testformats.PositionToEnd
import kotlin.test.*
import okio.FileSystem
import okio.Path.Companion.toPath
import okio.SYSTEM

class TestPositionToEnd {
    val SRC_DIR = FileSystem.SYSTEM.canonicalize("../../../src/".toPath(true))

    @Test
    fun testPositionToEnd() {
        val path = SRC_DIR.resolve("position_to_end.bin").toString()
        val r: PositionToEnd = PositionToEnd.fromFile(path)

        assertEquals(actual = r.index().foo(), expected = 66)
        assertEquals(actual = r.index().bar(), expected = 4660)
    }
}
