// Autogenerated from KST: please remove this line if doing any edits by hand!

package io.kaitai.struct.spec

import io.kaitai.struct.typing.*
import io.kaitai.struct.testformats.RepeatNStrzDouble
import kotlin.test.*
import okio.FileSystem
import okio.Path.Companion.toPath
import okio.SYSTEM

class TestRepeatNStrzDouble {
    val SRC_DIR = FileSystem.SYSTEM.canonicalize("../../../src/".toPath(true))

    @Test
    fun testRepeatNStrzDouble() {
        val path = SRC_DIR.resolve("repeat_n_strz.bin").toString()
        val r: RepeatNStrzDouble = RepeatNStrzDouble.fromFile(path)

        assertEquals(actual = r.qty(), expected = 2)
        assertContentEquals(actual = r.lines1(), expected = arrayListOf("foo"))
        assertContentEquals(actual = r.lines2(), expected = arrayListOf("bar"))
    }
}
