// Autogenerated from KST: please remove this line if doing any edits by hand!

package io.kaitai.struct.spec

import io.kaitai.struct.typing.*
import io.kaitai.struct.testformats.EnumInvalid
import kotlin.test.*
import okio.FileSystem
import okio.Path.Companion.toPath
import okio.SYSTEM

class TestEnumInvalid {
    val SRC_DIR = FileSystem.SYSTEM.canonicalize("../../../src/".toPath(true))

    @Test
    fun testEnumInvalid() {
        val path = SRC_DIR.resolve("term_strz.bin").toString()
        val r: EnumInvalid = EnumInvalid.fromFile(path)

        assertEquals(actual = r.pet1(), expected = EnumInvalid.Animal.DOG)
        assertEquals(actual = r.pet2(), expected = 111)
    }
}
